// Textes communs : navigation, pied de page, formulaires, libelles partages,
// metadonnees SEO. Version francaise, reference des traductions.
export default {
  skip: 'Aller au contenu',

  nav: {
    items: {
      home: 'Accueil',
      itineraries: 'Itinéraires',
      japon: 'Le Japon',
      guide: 'Guide pratique',
      about: 'Notre approche',
      journal: 'Journal',
    },
    cse: 'CSE',
    cta: 'Contactez-nous',
    menu: 'Menu',
    sousTitre: 'Itinéraires',
    langue: 'Langue',
    changerLangue: 'Choisir la langue',
  },

  mega: [
    { key: 'signatures', label: 'Signatures', target: ['itineraries'],
      note: 'Nos huit itinéraires longs, de sept à vingt-deux jours',
      links: [
        { label: 'Du Néon au Silence · 14 j', go: ['detail', 'CL-01'] },
        { label: 'Mille Marches vers le Nord · 14 j', go: ['detail', 'CL-02'] },
        { label: 'Des Temples aux Coraux · 14 j', go: ['detail', 'CL-03'] },
        { label: 'Le Premier Souffle · 7 j', go: ['detail', 'CL-04'] },
        { label: 'Au Cœur du Vieux Japon · 7 j', go: ['detail', 'CL-05'] },
        { label: 'La Traversée sans Hâte · 21 j', go: ['detail', 'CL-06'] },
        { label: 'Des Tours aux Toits de Chaume · 21 j', go: ['detail', 'CL-07'] },
        { label: "Jusqu'aux Cèdres Millénaires · 22 j", go: ['detail', 'CL-08'] },
      ],
      more: { label: 'Tous nos itinéraires signatures', go: ['itineraries'] } },
    { key: 'libertes', label: 'Séjours libertés', target: ['itineraries'],
      note: 'Journées prêtes à vivre, sans guide, à votre rythme',
      links: [
        { label: 'Le Tokyo des Néons', go: ['itineraries'] },
        { label: "Le Tokyo d'Edo", go: ['itineraries'] },
        { label: "Le Tokyo de l'Imaginaire", go: ['itineraries'] },
        { label: 'Kyoto Centre', go: ['itineraries'] },
        { label: 'Kyoto Est, le Chemin des Philosophes', go: ['itineraries'] },
        { label: 'Osaka Populaire', go: ['itineraries'] },
        { label: 'Enoshima et Kamakura', go: ['itineraries'] },
        { label: "L'Été des Ryukyu", go: ['itineraries'] },
      ],
      more: { label: 'Les seize séjours libertés', go: ['itineraries'] } },
    { key: 'groupe', label: 'Séjours en groupe', target: ['itineraries'],
      note: 'Quatre à huit voyageurs, accompagnés du départ au retour',
      links: [
        { label: 'Traversée des Alpes japonaises · 12 j', go: ['detail', 'CL-09'] },
        { label: 'Nos départs à venir', go: ['contact'] },
        { label: 'Voyager en petit groupe', go: ['about'] },
      ],
      more: { label: 'Nous écrire pour un départ', go: ['contact'] } },
    { key: 'sur-mesure', label: 'Sur-mesure', target: ['contact'],
      note: 'Un itinéraire écrit pour vous, à partir de vos envies',
      links: [
        { label: 'Comment nous travaillons', go: ['about'] },
        { label: 'Ce qui est toujours inclus', go: ['guide'] },
      ],
      more: { label: 'Demander une proposition', go: ['contact'] } },
  ],

  footer: {
    baseline: 'Des voyages au Japon retissés autour de vous, au rythme des saisons. De un à huit voyageurs en privé, de quatre à huit en petit groupe.',
    colItin: 'Itinéraires',
    colMaison: 'Maison',
    colSuivre: 'Suivre',
    signatures: 'Signatures',
    libertes: 'Séjours libertés',
    groupe: 'Séjours en groupe',
    surMesure: 'Sur-mesure',
    japon: 'Le Japon',
    histoire: 'Histoire',
    gastronomie: 'Gastronomie',
    guide: 'Guide pratique',
    about: 'Notre approche',
    journal: 'Le journal',
    cse: "Comités d'entreprise, CSE",
    contact: 'Nous écrire',
    atout: 'Immatriculée Atout France sous le n° IM075260052',
    copyright: '© 2026 Kiraku Travel · IM075260052 · Paris et partout au Japon',
    mentions: 'Mentions légales',
    cgv: 'CGV',
    confidentialite: 'Confidentialité',
    realise: 'Site réalisé par',
  },

  ui: {
    voirItineraires: 'Voir les itinéraires',
    notreApproche: 'Notre approche →',
    imageN: 'Image',
    photoN: 'Photo',
    photoPrecedente: 'Photo précédente',
    photoSuivante: 'Photo suivante',
    moisPrecedent: 'Mois précédent',
    moisSuivant: 'Mois suivant',
    retirer: 'Retirer',
    ajouter: 'Ajouter',
    kiraku: 'Kiraku',
    fil: 'Itinéraires',
  },

  detail: {
    aPartirDe: 'À partir de',
    leCircuitEnBref: 'Le circuit en bref',
    reserverAppel: 'Réserver un appel',
    noteAppel: 'Trente minutes au téléphone. Sans engagement.',
    essentielEyebrow: "L'ESSENTIEL",
    essentielTitre: 'Ce qu\'il faut savoir avant de choisir.',
    jour: 'JOUR',
    sejourEyebrow: 'VOTRE SÉJOUR EN DÉTAILS',
    sejourTitre: 'Les points importants.',
    detailEyebrow: 'LE DÉTAIL DU SÉJOUR',
    tabs: {
      forts: 'Points forts',
      heb: 'Vos hébergements',
      tr: 'Vos transports',
      guide: 'Guide',
      equip: "L'équipement",
      options: 'Options et suppléments',
      savoir: 'Bon à savoir',
      inclus: 'Inclus',
      exclus: 'Non inclus',
      departs: 'Départs et prix',
    },
    thDepart: 'Départ',
    thRetour: 'Retour',
    thAdulte: 'Adulte',
    inclusEyebrow: 'CE QUI EST INCLUS',
    inclusTitre: 'Compris et non compris dans le prix.',
    colInclus: 'Inclus',
    colExclus: 'Non inclus',
    optionsEyebrow: 'SUPPLÉMENTS ET OPTIONS',
    formulePrive: 'Voyage sur-mesure',
    formuleGroupe: 'Circuit accompagné',
  },

  booking: {
    enGroupe: 'En groupe',
    enPrive: 'En privé',
    retourLe: 'retour le',
    aucuneDate: 'Aucune date de groupe publiée. Nous en ouvrons une à partir de quatre voyageurs.',
    departLe: 'Départ le',
    retourLePhrase: 'retour le',
    voyageurs: 'Voyageurs',
    voyageursSubGroupe: 'quatre minimum en groupe',
    voyageursSubPrive: '13 ans et plus',
    enfants: 'Enfants',
    enfantsSub: 'moins de 13 ans',
    bebes: 'Bébés',
    bebesSub: 'moins de 2 ans',
    chambres: 'Chambres',
    chambresAuto: 'deux par chambre',
    chambresManuel: 'à votre demande',
    estimation: 'Estimation',
    voyagePrive: 'Voyage privé',
    surDevis: 'Sur devis',
    demanderDate: 'Demander cette date',
    demanderDevis: 'Demander un devis',
    choisirDateListe: 'Choisissez une date ci-dessus. Aucun paiement à cette étape.',
    choisirDateCal: 'Choisissez une date au calendrier. Aucun paiement à cette étape.',
    recapVoyageur: 'voyageur',
    recapVoyageurs: 'voyageurs',
    recapEt: 'et',
    recapBebe: 'bébé',
    recapBebes: 'bébés',
    recapChambre: 'chambre',
    recapChambres: 'chambres',
    recapFin: 'Aucun paiement à cette étape.',
    calNote: 'Grisé : janvier, février, Golden Week, Obon et Nouvel An.',
    mois: ['janvier','février','mars','avril','mai','juin','juillet','août','septembre','octobre','novembre','décembre'],
    moisCourt: ['janv.','févr.','mars','avril','mai','juin','juil.','août','sept.','oct.','nov.','déc.'],
    joursL: ['L','M','M','J','V','S','D'],
    locale: 'fr-FR',
  },

  form: {
    obligatoire: 'obligatoire',
    envoiEnCours: 'Envoi en cours…',
    envoyer: 'Envoyer la demande',
    reponse48: 'Réponse sous 48 h ouvrées.',
    vouliezVousDire: 'Vouliez-vous dire',
    nePasRemplir: 'Ne pas remplir',
    manqueUne: "Il manque une information avant l'envoi. Les champs en rouge sont à compléter.",
    manquePlusieurs: "Il manque {n} informations avant l'envoi. Les champs en rouge sont à compléter.",
  },

  validation: {
    prenomRequis: 'Votre prénom est requis.',
    nomRequis: 'Votre nom est requis.',
    emailRequis: 'Votre email est requis.',
    emailLong: 'Cette adresse est trop longue.',
    emailInvalide: "Cet email ne semble pas valide, vérifiez la partie après le @.",
    emailJetable: "Les adresses temporaires ne sont pas acceptées, indiquez une adresse que vous consultez.",
    telRequis: 'Votre téléphone portable est requis.',
    telIntlInvalide: 'Ce numéro international ne semble pas valide.',
    telInexistant: "Ce numéro n'existe pas, vérifiez les chiffres.",
    telZeroApres33: "Après +33, le zéro ne se met pas : +33 6 45 78 21 09.",
    telNeufChiffres: 'Un numéro français compte neuf chiffres après le +33.',
    telMobile33: 'Indiquez un mobile, il commence par 6 ou 7 après le +33.',
    telIncomplet: 'Ce numéro ne semble pas complet.',
    telCommencePar: "Commencez par 0 pour un numéro français, ou par + pour l'étranger.",
    telManqueUn: 'Il manque un chiffre, un numéro français en compte dix.',
    telManquePlusieurs: 'Il manque {n} chiffres, un numéro français en compte dix.',
    telDixChiffres: 'Un numéro français compte dix chiffres.',
    telPrefixe: "Ce préfixe n'est pas attribué aux particuliers.",
    telMobile06: 'Indiquez un mobile, il commence par 06 ou 07.',
    reseau: "L'envoi n'a pas abouti. Vérifiez votre connexion et réessayez, ou écrivez-nous à contact@kirakutravel.com.",
  },

  seo: {
    home: {
      titre: 'Kiraku Travel · Voyages sur-mesure au Japon, de un à huit voyageurs',
      description: "Agence de voyage française spécialisée sur le Japon. Itinéraires privés et petits groupes, écrits main dans la main avec vous, du Tokyo des néons aux cèdres millénaires.",
    },
    itineraries: {
      titre: 'Nos itinéraires au Japon · Kiraku Travel',
      description: "Huit itinéraires signatures de sept à vingt-deux jours, seize séjours libertés et une extension à Okinawa. Tous adaptables, tous en voyage privé.",
    },
    japon: {
      titre: 'Le Japon avant le voyage · Kiraku Travel',
      description: "Comprendre le pays avant d'y aller : son histoire en trois ères, sa géographie racontée dans l'assiette, et ce que cela change à votre itinéraire.",
    },
    'japon-histoire': {
      titre: "Histoire du Japon, de Heian à Meiji · Kiraku Travel",
      description: "Heian, Edo, Meiji : trois ères qui expliquent les villes, les temples et les paysages que vous allez traverser.",
    },
    'japon-gastronomie': {
      titre: 'Gastronomie japonaise, préfecture par préfecture · Kiraku Travel',
      description: "Tokyo, Kyoto, Osaka : ce que l'on mange, où, et pourquoi la géographie du Japon se lit dans l'assiette.",
    },
    guide: {
      titre: 'Guide pratique du Japon, métro, Suica, hiragana · Kiraku Travel',
      description: "La boîte à outils du voyage : métro et Shinkansen, carte Suica, usage des baguettes, hiragana, katakana, quinze kanji et trente phrases utiles.",
    },
    about: {
      titre: 'Notre approche du voyage au Japon · Kiraku Travel',
      description: "Ce que nous ne faisons pas, ce que nous faisons, et pourquoi nos itinéraires laissent de la place au vide.",
    },
    journal: {
      titre: 'Le journal · Kiraku Travel',
      description: "Carnets de repérage, rencontres d'artisans et notes de saison, écrits depuis le Japon.",
    },
    cse: {
      titre: "Voyages au Japon pour CSE et comités d'entreprise · Kiraku Travel",
      description: "Offres dédiées aux comités sociaux et économiques : dotations, tarifs négociés, accompagnement des salariés et supports de communication prêts à diffuser.",
    },
    contact: {
      titre: 'Nous écrire · Kiraku Travel',
      description: "Trente minutes au téléphone, sans engagement, pour parler de votre voyage au Japon.",
    },
    cgv: {
      titre: 'CGV et mentions légales · Kiraku Travel',
      description: "Conditions générales de vente, mentions légales et informations réglementaires de Kiraku Travel, immatriculée Atout France IM075260052.",
    },
    circuitTitre: (titre, duree) => `${titre}, ${duree} au Japon · Kiraku Travel`,
    circuitDescription: (titre, duree) => `${titre}, itinéraire de ${duree} au Japon, écrit et accompagné par Kiraku Travel. Jour par jour, hébergements choisis, rythme sans hâte.`,
    circuitDefautTitre: 'Itinéraire au Japon · Kiraku Travel',
    circuitDefautDescription: 'Itinéraire sur-mesure au Japon avec Kiraku Travel.',
  },
};
