// Textos comunes: navegación, pie de página, formularios, etiquetas compartidas,
// metadatos SEO. Versión española, traducida de common.fr.js.
export default {
  skip: 'Ir al contenido',

  nav: {
    items: {
      home: 'Inicio',
      itineraries: 'Itinerarios',
      japon: 'Japón',
      guide: 'Guía práctica',
      about: 'Nuestro enfoque',
      journal: 'Diario',
    },
    cse: 'Comités',
    cta: 'Contáctenos',
    menu: 'Menú',
    sousTitre: 'Itinerarios',
    langue: 'Idioma',
    changerLangue: 'Elegir el idioma',
  },

  mega: [
    { key: 'signatures', label: 'Firmas', target: ['itineraries'],
      note: 'Nuestros ocho itinerarios largos, de siete a veintidós días',
      links: [
        { label: 'Del Neón al Silencio · 14 días', go: ['detail', 'CL-01'] },
        { label: 'Mil Escalones hacia el Norte · 14 días', go: ['detail', 'CL-02'] },
        { label: 'De los Templos a los Corales · 14 días', go: ['detail', 'CL-03'] },
        { label: 'El Primer Aliento · 7 días', go: ['detail', 'CL-04'] },
        { label: 'El Corazón del Viejo Japón · 7 días', go: ['detail', 'CL-05'] },
        { label: 'La Travesía sin Prisa · 21 días', go: ['detail', 'CL-06'] },
        { label: 'De las Torres a los Tejados de Paja · 21 días', go: ['detail', 'CL-07'] },
        { label: 'Hasta los Cedros Milenarios · 22 días', go: ['detail', 'CL-08'] },
      ],
      more: { label: 'Todos nuestros itinerarios firma', go: ['itineraries'] } },
    { key: 'libertes', label: 'Estancias libres', target: ['itineraries'],
      note: 'Jornadas listas para vivir, sin guía, a su ritmo',
      links: [
        { label: 'El Tokio de los Neones', go: ['itineraries'] },
        { label: 'El Tokio de Edo', go: ['itineraries'] },
        { label: 'El Tokio de la Imaginación', go: ['itineraries'] },
        { label: 'Kioto Centro', go: ['itineraries'] },
        { label: 'Kioto Este, el Camino del Filósofo', go: ['itineraries'] },
        { label: 'Osaka Popular', go: ['itineraries'] },
        { label: 'Enoshima y Kamakura', go: ['itineraries'] },
        { label: 'El Verano de las Ryukyu', go: ['itineraries'] },
      ],
      more: { label: 'Las dieciséis estancias libres', go: ['itineraries'] } },
    { key: 'groupe', label: 'Estancias en grupo', target: ['itineraries'],
      note: 'De cuatro a ocho viajeros, acompañados de la salida al regreso',
      links: [
        { label: 'Travesía de los Alpes Japoneses · 12 días', go: ['detail', 'CL-09'] },
        { label: 'Nuestras próximas salidas', go: ['contact'] },
        { label: 'Viajar en grupo reducido', go: ['about'] },
      ],
      more: { label: 'Escríbanos para una salida', go: ['contact'] } },
    { key: 'sur-mesure', label: 'A medida', target: ['contact'],
      note: 'Un itinerario escrito para usted, a partir de sus deseos',
      links: [
        { label: 'Cómo trabajamos', go: ['about'] },
        { label: 'Lo que siempre está incluido', go: ['guide'] },
      ],
      more: { label: 'Solicitar una propuesta', go: ['contact'] } },
  ],

  footer: {
    baseline: 'Viajes por Japón tejidos de nuevo en torno a usted, al ritmo de las estaciones. De uno a ocho viajeros en privado, de cuatro a ocho en grupo reducido.',
    colItin: 'Itinerarios',
    colMaison: 'La casa',
    colSuivre: 'Seguir',
    signatures: 'Firmas',
    libertes: 'Estancias libres',
    groupe: 'Estancias en grupo',
    surMesure: 'A medida',
    japon: 'Japón',
    histoire: 'Historia',
    gastronomie: 'Gastronomía',
    guide: 'Guía práctica',
    about: 'Nuestro enfoque',
    journal: 'El diario',
    cse: 'Comités de empresa',
    contact: 'Escríbanos',
    atout: 'Inscrita en Atout France con el n.º IM075260052',
    copyright: '© 2026 Kiraku Travel · IM075260052 · Paris y por todo Japón',
    mentions: 'Aviso legal',
    cgv: 'Condiciones generales',
    confidentialite: 'Privacidad',
    realise: 'Sitio realizado por',
  },

  ui: {
    voirItineraires: 'Ver los itinerarios',
    notreApproche: 'Nuestro enfoque →',
    imageN: 'Imagen',
    photoN: 'Foto',
    photoPrecedente: 'Foto anterior',
    photoSuivante: 'Foto siguiente',
    moisPrecedent: 'Mes anterior',
    moisSuivant: 'Mes siguiente',
    retirer: 'Quitar',
    ajouter: 'Añadir',
    kiraku: 'Kiraku',
    fil: 'Itinerarios',
  },

  detail: {
    aPartirDe: 'Desde',
    leCircuitEnBref: 'El circuito en breve',
    reserverAppel: 'Reservar una llamada',
    noteAppel: 'Treinta minutos por teléfono. Sin compromiso.',
    essentielEyebrow: 'LO ESENCIAL',
    essentielTitre: 'Lo que conviene saber antes de elegir.',
    jour: 'DÍA',
    sejourEyebrow: 'SU ESTANCIA EN DETALLE',
    sejourTitre: 'Los puntos importantes.',
    detailEyebrow: 'EL DETALLE DE LA ESTANCIA',
    tabs: {
      forts: 'Puntos fuertes',
      heb: 'Sus alojamientos',
      tr: 'Sus transportes',
      guide: 'Guía',
      equip: 'El equipamiento',
      options: 'Opciones y suplementos',
      savoir: 'Conviene saber',
      inclus: 'Incluido',
      exclus: 'No incluido',
      departs: 'Salidas y precios',
    },
    thDepart: 'Salida',
    thRetour: 'Regreso',
    thAdulte: 'Adulto',
    inclusEyebrow: 'LO QUE ESTÁ INCLUIDO',
    inclusTitre: 'Lo que comprende el precio y lo que no.',
    colInclus: 'Incluido',
    colExclus: 'No incluido',
    optionsEyebrow: 'SUPLEMENTOS Y OPCIONES',
    formulePrive: 'Viaje a medida',
    formuleGroupe: 'Circuito acompañado',
  },

  booking: {
    enGroupe: 'En grupo',
    enPrive: 'En privado',
    retourLe: 'regreso el',
    aucuneDate: 'No hay ninguna fecha de grupo publicada. Abrimos una a partir de cuatro viajeros.',
    departLe: 'Salida el',
    retourLePhrase: 'regreso el',
    voyageurs: 'Viajeros',
    voyageursSubGroupe: 'cuatro como mínimo en grupo',
    voyageursSubPrive: '13 años o más',
    enfants: 'Niños',
    enfantsSub: 'menos de 13 años',
    bebes: 'Bebés',
    bebesSub: 'menos de 2 años',
    chambres: 'Habitaciones',
    chambresAuto: 'dos por habitación',
    chambresManuel: 'según su petición',
    estimation: 'Estimación',
    voyagePrive: 'Viaje privado',
    surDevis: 'Bajo presupuesto',
    demanderDate: 'Solicitar esta fecha',
    demanderDevis: 'Solicitar un presupuesto',
    choisirDateListe: 'Elija una fecha más arriba. Ningún pago en esta etapa.',
    choisirDateCal: 'Elija una fecha en el calendario. Ningún pago en esta etapa.',
    recapVoyageur: 'viajero',
    recapVoyageurs: 'viajeros',
    recapEt: 'y',
    recapBebe: 'bebé',
    recapBebes: 'bebés',
    recapChambre: 'habitación',
    recapChambres: 'habitaciones',
    recapFin: 'Ningún pago en esta etapa.',
    calNote: 'En gris: enero, febrero, Golden Week, Obon y Año Nuevo.',
    mois: ['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'],
    moisCourt: ['ene.','feb.','mar.','abr.','mayo','jun.','jul.','ago.','sept.','oct.','nov.','dic.'],
    joursL: ['L','M','X','J','V','S','D'],
    locale: 'es-ES',
  },

  form: {
    obligatoire: 'obligatorio',
    envoiEnCours: 'Enviando…',
    envoyer: 'Enviar la solicitud',
    reponse48: 'Respuesta en 48 h laborables.',
    vouliezVousDire: '¿Quería decir',
    nePasRemplir: 'No rellenar',
    manqueUne: 'Falta una información antes del envío. Los campos en rojo están por completar.',
    manquePlusieurs: 'Faltan {n} informaciones antes del envío. Los campos en rojo están por completar.',
  },

  validation: {
    prenomRequis: 'Su nombre es obligatorio.',
    nomRequis: 'Sus apellidos son obligatorios.',
    emailRequis: 'Su correo electrónico es obligatorio.',
    emailLong: 'Esta dirección es demasiado larga.',
    emailInvalide: 'Este correo no parece válido, compruebe la parte posterior a la @.',
    emailJetable: 'No se aceptan direcciones temporales, indique una dirección que consulte.',
    telRequis: 'Su teléfono móvil es obligatorio.',
    telIntlInvalide: 'Este número internacional no parece válido.',
    telInexistant: 'Este número no existe, compruebe las cifras.',
    telZeroApres33: 'Después de +33, el cero no se escribe: +33 6 45 78 21 09.',
    telNeufChiffres: 'Un número francés tiene nueve cifras después del +33.',
    telMobile33: 'Indique un móvil, empieza por 6 o 7 después del +33.',
    telIncomplet: 'Este número no parece completo.',
    telCommencePar: 'Empiece por 0 para un número francés, o por + para el extranjero.',
    telManqueUn: 'Falta una cifra, un número francés tiene diez.',
    telManquePlusieurs: 'Faltan {n} cifras, un número francés tiene diez.',
    telDixChiffres: 'Un número francés tiene diez cifras.',
    telPrefixe: 'Este prefijo no está asignado a particulares.',
    telMobile06: 'Indique un móvil, empieza por 06 o 07.',
    reseau: 'El envío no se ha completado. Compruebe su conexión e inténtelo de nuevo, o escríbanos a contact@kirakutravel.com.',
  },

  seo: {
    home: {
      titre: 'Kiraku Travel · Viajes a medida por Japón, de uno a ocho viajeros',
      description: 'Agencia de viajes francesa especializada en Japón. Itinerarios privados y grupos reducidos, escritos mano a mano con usted, del Tokio de los neones a los cedros milenarios.',
    },
    itineraries: {
      titre: 'Nuestros itinerarios por Japón · Kiraku Travel',
      description: 'Ocho itinerarios firma de siete a veintidós días, dieciséis estancias libres y una extensión a Okinawa. Todos adaptables, todos en viaje privado.',
    },
    japon: {
      titre: 'Japón antes del viaje · Kiraku Travel',
      description: 'Comprender el país antes de ir: su historia en tres eras, su geografía contada en el plato y lo que eso cambia en su itinerario.',
    },
    'japon-histoire': {
      titre: 'Historia de Japón, de Heian a Meiji · Kiraku Travel',
      description: 'Heian, Edo, Meiji: tres eras que explican las ciudades, los templos y los paisajes que va a recorrer.',
    },
    'japon-gastronomie': {
      titre: 'Gastronomía japonesa, prefectura por prefectura · Kiraku Travel',
      description: 'Tokio, Kioto, Osaka: qué se come, dónde y por qué la geografía de Japón se lee en el plato.',
    },
    guide: {
      titre: 'Guía práctica de Japón, metro, Suica, hiragana · Kiraku Travel',
      description: 'La caja de herramientas del viaje: metro y Shinkansen, tarjeta Suica, uso de los palillos, hiragana, katakana, quince kanji y treinta frases útiles.',
    },
    about: {
      titre: 'Nuestro enfoque del viaje por Japón · Kiraku Travel',
      description: 'Lo que no hacemos, lo que sí hacemos y por qué nuestros itinerarios dejan sitio al vacío.',
    },
    journal: {
      titre: 'El diario · Kiraku Travel',
      description: 'Cuadernos de exploración, encuentros con artesanos y notas de temporada, escritos desde Japón.',
    },
    cse: {
      titre: 'Viajes a Japón para comités de empresa · Kiraku Travel',
      description: 'Ofertas dedicadas a los comités de empresa: dotaciones, tarifas negociadas, acompañamiento de los empleados y materiales de comunicación listos para difundir.',
    },
    contact: {
      titre: 'Escríbanos · Kiraku Travel',
      description: 'Treinta minutos por teléfono, sin compromiso, para hablar de su viaje a Japón.',
    },
    cgv: {
      titre: 'Condiciones generales y aviso legal · Kiraku Travel',
      description: 'Condiciones generales de venta, aviso legal e información reglamentaria de Kiraku Travel, inscrita en Atout France con el número IM075260052.',
    },
    circuitTitre: (titre, duree) => `${titre}, ${duree} por Japón · Kiraku Travel`,
    circuitDescription: (titre, duree) => `${titre}, itinerario de ${duree} por Japón, escrito y acompañado por Kiraku Travel. Día a día, alojamientos elegidos, ritmo sin prisa.`,
    circuitDefautTitre: 'Itinerario por Japón · Kiraku Travel',
    circuitDefautDescription: 'Itinerario a medida por Japón con Kiraku Travel.',
  },
};
