// Shared copy: navigation, footer, forms, common labels,
// SEO metadata. British English version, translated from common.fr.js.
export default {
  skip: 'Skip to content',

  nav: {
    items: {
      home: 'Home',
      itineraries: 'Itineraries',
      japon: 'Japan',
      guide: 'Practical guide',
      about: 'Our approach',
      journal: 'Journal',
    },
    cse: 'Works councils',
    cta: 'Contact us',
    menu: 'Menu',
    sousTitre: 'Itineraries',
    langue: 'Language',
    changerLangue: 'Choose the language',
  },

  mega: [
    { key: 'signatures', label: 'Signatures', target: ['itineraries'],
      note: 'Our eight long itineraries, from seven to twenty-two days',
      links: [
        { label: 'From Neon to Silence · 14 days', go: ['detail', 'CL-01'] },
        { label: 'A Thousand Steps North · 14 days', go: ['detail', 'CL-02'] },
        { label: 'From Temples to Coral · 14 days', go: ['detail', 'CL-03'] },
        { label: 'The First Breath · 7 days', go: ['detail', 'CL-04'] },
        { label: 'The Heart of Old Japan · 7 days', go: ['detail', 'CL-05'] },
        { label: 'The Unhurried Crossing · 21 days', go: ['detail', 'CL-06'] },
        { label: 'From Towers to Thatched Roofs · 21 days', go: ['detail', 'CL-07'] },
        { label: 'To the Thousand Year Cedars · 22 days', go: ['detail', 'CL-08'] },
      ],
      more: { label: 'All our signature itineraries', go: ['itineraries'] } },
    { key: 'libertes', label: 'Freedom stays', target: ['itineraries'],
      note: 'Days ready to be lived, without a guide, at your own pace',
      links: [
        { label: 'Neon Tokyo', go: ['itineraries'] },
        { label: 'Edo Tokyo', go: ['itineraries'] },
        { label: 'Tokyo of the Imagination', go: ['itineraries'] },
        { label: 'Central Kyoto', go: ['itineraries'] },
        { label: "East Kyoto, the Philosopher's Path", go: ['itineraries'] },
        { label: 'Downtown Osaka', go: ['itineraries'] },
        { label: 'Enoshima and Kamakura', go: ['itineraries'] },
        { label: 'A Ryukyu Summer', go: ['itineraries'] },
      ],
      more: { label: 'The sixteen freedom stays', go: ['itineraries'] } },
    { key: 'groupe', label: 'Group trips', target: ['itineraries'],
      note: 'Four to eight travellers, accompanied from departure to return',
      links: [
        { label: 'Japanese Alps Traverse · 12 days', go: ['detail', 'CL-09'] },
        { label: 'Our upcoming departures', go: ['contact'] },
        { label: 'Travelling in a small group', go: ['about'] },
      ],
      more: { label: 'Write to us about a departure', go: ['contact'] } },
    { key: 'sur-mesure', label: 'Bespoke', target: ['contact'],
      note: 'An itinerary written for you, starting from what you long for',
      links: [
        { label: 'How we work', go: ['about'] },
        { label: 'What is always included', go: ['guide'] },
      ],
      more: { label: 'Request a proposal', go: ['contact'] } },
  ],

  footer: {
    baseline: 'Journeys through Japan rewoven around you, in step with the seasons. One to eight travellers in private, four to eight in a small group.',
    colItin: 'Itineraries',
    colMaison: 'The house',
    colSuivre: 'Follow',
    signatures: 'Signatures',
    libertes: 'Freedom stays',
    groupe: 'Group trips',
    surMesure: 'Bespoke',
    japon: 'Japan',
    histoire: 'History',
    gastronomie: 'Gastronomy',
    guide: 'Practical guide',
    about: 'Our approach',
    journal: 'The journal',
    cse: 'Works councils',
    contact: 'Write to us',
    atout: 'Registered with Atout France under no. IM075260052',
    copyright: '© 2026 Kiraku Travel · IM075260052 · Paris and everywhere in Japan',
    mentions: 'Legal notice',
    cgv: 'Terms of sale',
    confidentialite: 'Privacy',
    realise: 'Site built by',
  },

  ui: {
    voirItineraires: 'See the itineraries',
    notreApproche: 'Our approach →',
    imageN: 'Image',
    photoN: 'Photo',
    photoPrecedente: 'Previous photo',
    photoSuivante: 'Next photo',
    moisPrecedent: 'Previous month',
    moisSuivant: 'Next month',
    retirer: 'Remove',
    ajouter: 'Add',
    kiraku: 'Kiraku',
    fil: 'Itineraries',
  },

  detail: {
    aPartirDe: 'From',
    leCircuitEnBref: 'The trip at a glance',
    reserverAppel: 'Book a call',
    noteAppel: 'Thirty minutes on the phone. No commitment.',
    essentielEyebrow: 'THE ESSENTIALS',
    essentielTitre: 'What to know before you choose.',
    jour: 'DAY',
    sejourEyebrow: 'YOUR STAY IN DETAIL',
    sejourTitre: 'The points that matter.',
    detailEyebrow: 'THE DETAIL OF THE STAY',
    tabs: {
      forts: 'Highlights',
      heb: 'Your accommodation',
      tr: 'Your transport',
      guide: 'Guide',
      equip: 'Equipment',
      options: 'Options and supplements',
      savoir: 'Good to know',
      inclus: 'Included',
      exclus: 'Not included',
      departs: 'Departures and prices',
    },
    thDepart: 'Departure',
    thRetour: 'Return',
    thAdulte: 'Adult',
    inclusEyebrow: 'WHAT IS INCLUDED',
    inclusTitre: 'What the price covers, and what it does not.',
    colInclus: 'Included',
    colExclus: 'Not included',
    optionsEyebrow: 'SUPPLEMENTS AND OPTIONS',
    formulePrive: 'Bespoke journey',
    formuleGroupe: 'Escorted trip',
  },

  booking: {
    enGroupe: 'In a group',
    enPrive: 'In private',
    retourLe: 'returning on',
    aucuneDate: 'No group date published. We open one from four travellers.',
    departLe: 'Departing on',
    retourLePhrase: 'returning on',
    voyageurs: 'Travellers',
    voyageursSubGroupe: 'four minimum in a group',
    voyageursSubPrive: '13 years and over',
    enfants: 'Children',
    enfantsSub: 'under 13',
    bebes: 'Infants',
    bebesSub: 'under 2',
    chambres: 'Rooms',
    chambresAuto: 'two per room',
    chambresManuel: 'at your request',
    estimation: 'Estimate',
    voyagePrive: 'Private journey',
    surDevis: 'On request',
    demanderDate: 'Request this date',
    demanderDevis: 'Request a quote',
    choisirDateListe: 'Choose a date above. No payment at this stage.',
    choisirDateCal: 'Choose a date on the calendar. No payment at this stage.',
    recapVoyageur: 'traveller',
    recapVoyageurs: 'travellers',
    recapEt: 'and',
    recapBebe: 'infant',
    recapBebes: 'infants',
    recapChambre: 'room',
    recapChambres: 'rooms',
    recapFin: 'No payment at this stage.',
    calNote: 'Greyed out: January, February, Golden Week, Obon and New Year.',
    mois: ['January','February','March','April','May','June','July','August','September','October','November','December'],
    moisCourt: ['Jan.','Feb.','Mar.','Apr.','May','Jun.','Jul.','Aug.','Sept.','Oct.','Nov.','Dec.'],
    joursL: ['M','T','W','T','F','S','S'],
    locale: 'en-GB',
  },

  form: {
    obligatoire: 'required',
    envoiEnCours: 'Sending…',
    envoyer: 'Send the request',
    reponse48: 'Reply within 48 working hours.',
    vouliezVousDire: 'Did you mean',
    nePasRemplir: 'Do not fill in',
    manqueUne: 'One piece of information is missing before sending. The fields in red need completing.',
    manquePlusieurs: '{n} pieces of information are missing before sending. The fields in red need completing.',
  },

  validation: {
    prenomRequis: 'Your first name is required.',
    nomRequis: 'Your surname is required.',
    emailRequis: 'Your email is required.',
    emailLong: 'This address is too long.',
    emailInvalide: 'This email does not look valid, check the part after the @.',
    emailJetable: 'Temporary addresses are not accepted, please give an address you actually read.',
    telRequis: 'Your mobile number is required.',
    telIntlInvalide: 'This international number does not look valid.',
    telInexistant: 'This number does not exist, check the digits.',
    telZeroApres33: 'After +33, the zero is dropped: +33 6 45 78 21 09.',
    telNeufChiffres: 'A French number has nine digits after +33.',
    telMobile33: 'Please give a mobile, it starts with 6 or 7 after +33.',
    telIncomplet: 'This number does not look complete.',
    telCommencePar: 'Start with 0 for a French number, or with + from abroad.',
    telManqueUn: 'One digit is missing, a French number has ten.',
    telManquePlusieurs: '{n} digits are missing, a French number has ten.',
    telDixChiffres: 'A French number has ten digits.',
    telPrefixe: 'This prefix is not allocated to individuals.',
    telMobile06: 'Please give a mobile, it starts with 06 or 07.',
    reseau: 'The message could not be sent. Check your connection and try again, or write to us at contact@kirakutravel.com.',
  },

  seo: {
    home: {
      titre: 'Kiraku Travel · Bespoke journeys in Japan, one to eight travellers',
      description: 'A French travel agency specialising in Japan. Private itineraries and small groups, written hand in hand with you, from neon Tokyo to the thousand year cedars.',
    },
    itineraries: {
      titre: 'Our itineraries in Japan · Kiraku Travel',
      description: 'Eight signature itineraries from seven to twenty-two days, sixteen freedom stays and an extension to Okinawa. All adaptable, all as private journeys.',
    },
    japon: {
      titre: 'Japan before the journey · Kiraku Travel',
      description: 'Understanding the country before you go: its history in three eras, its geography told on the plate, and what that changes in your itinerary.',
    },
    'japon-histoire': {
      titre: 'History of Japan, from Heian to Meiji · Kiraku Travel',
      description: 'Heian, Edo, Meiji: three eras that explain the cities, the temples and the landscapes you will travel through.',
    },
    'japon-gastronomie': {
      titre: 'Japanese gastronomy, prefecture by prefecture · Kiraku Travel',
      description: 'Tokyo, Kyoto, Osaka: what people eat, where, and why the geography of Japan can be read on the plate.',
    },
    guide: {
      titre: 'Practical guide to Japan, metro, Suica, hiragana · Kiraku Travel',
      description: 'The travel toolkit: metro and Shinkansen, Suica card, using chopsticks, hiragana, katakana, fifteen kanji and thirty useful phrases.',
    },
    about: {
      titre: 'Our approach to travel in Japan · Kiraku Travel',
      description: 'What we do not do, what we do, and why our itineraries leave room for emptiness.',
    },
    journal: {
      titre: 'The journal · Kiraku Travel',
      description: 'Scouting notebooks, meetings with craftspeople and seasonal notes, written from Japan.',
    },
    cse: {
      titre: 'Trips to Japan for works councils and staff committees · Kiraku Travel',
      description: 'Dedicated offers for works councils: allowances, negotiated rates, support for employees and communication materials ready to share.',
    },
    contact: {
      titre: 'Write to us · Kiraku Travel',
      description: 'Thirty minutes on the phone, with no commitment, to talk about your journey in Japan.',
    },
    cgv: {
      titre: 'Terms of sale and legal notice · Kiraku Travel',
      description: 'General terms and conditions of sale, legal notice and regulatory information for Kiraku Travel, registered with Atout France under IM075260052.',
    },
    circuitTitre: (titre, duree) => `${titre}, ${duree} in Japan · Kiraku Travel`,
    circuitDescription: (titre, duree) => `${titre}, a ${duree} itinerary in Japan, written and accompanied by Kiraku Travel. Day by day, chosen accommodation, an unhurried pace.`,
    circuitDefautTitre: 'Itinerary in Japan · Kiraku Travel',
    circuitDefautDescription: 'Bespoke itinerary in Japan with Kiraku Travel.',
  },
};
