// Pagina comites de empresa. Version espanola, traducida de cse.fr.js.
export default {
  hero: {
    eyebrow: 'COMITÉS DE EMPRESA',
    titreAvant: 'Ofrezca a sus empleados un viaje del que hablarán ',
    titreBrush: 'durante años',
    titreApres: '.',
    lede: "Kiraku Travel diseña viajes a Japón para grupos de cuatro a ocho personas. Trabajamos con los comités de empresa que buscan algo distinto de un catálogo y que quieren una persona al otro lado del teléfono.",
    cta1: 'Solicitar un contacto',
    cta2: 'Ver lo que aportamos',
    photo: 'Callejón de Kioto al anochecer',
  },

  intro: {
    eyebrow: 'LA AGENCIA',
    titre: 'Una agencia pequeña, registrada, que explora ella misma sus itinerarios.',
    p1: "Kiraku Travel es una agencia independiente con sede en París, registrada en Atout France con el número IM075260052. No revendemos circuitos comprados en otro sitio: cada itinerario se explora sobre el terreno, estación por estación, posada por posada.",
    p2: "Nuestros tres principios se resumen en pocas palabras. Grupos pequeños, para que el lugar siga vivo. Ritmo lento, porque un viaje necesita tiempo para asentarse. Precios claros, todo queda por escrito antes de firmar.",
    facts: [
      { n: '8', t: 'itinerarios exclusivos, de 7 a 22 días' },
      { n: '4 a 8', t: 'viajeros por salida en grupo' },
      { n: '48 h', t: 'para responder a su solicitud en días laborables' },
    ],
    photo: "Taller de artesano, exploración sobre el terreno",
  },

  apports: {
    eyebrow: 'LO QUE APORTAMOS AL COMITÉ',
    titre: 'El comité mantiene el control, nosotros nos ocupamos de la logística.',
    items: [
      { n: '01', t: 'Una oferta negociada, sin coste adicional para el comité', p: "Tarifas de grupo en nuestros itinerarios exclusivos, con la misma prestación que reciben nuestros viajeros individuales. Ningún gasto de gestión facturado al comité." },
      { n: '02', t: 'Un único interlocutor desde el primer contacto hasta la vuelta', p: "Una persona que conoce su expediente, localizable por teléfono, que hace el seguimiento de las inscripciones, de los pagos a cuenta y de los imprevistos." },
      { n: '03', t: 'Materiales listos para difundir', p: "Carteles, fichas de itinerario, textos para su intranet y su boletín. Preparamos con usted la comunicación interna." },
      { n: '04', t: 'Una gestión de reservas flexible', p: "Salidas escalonadas, pago fraccionado, aportación del comité ajustable por empleado o por hogar." },
    ],
  },

  benefices: {
    eyebrow: 'LAS VENTAJAS PARA SUS EMPLEADOS',
    titre: "Un viaje que no parece un viaje de empresa.",
    items: [
      { n: '01', t: 'Grupos de cuatro a ocho personas', p: "Nunca un autocar, nunca un banderín. Trenes, posadas familiares, mesas donde uno se sienta con los habitantes." },
      { n: '02', t: 'Acompañamiento de habla hispana sobre el terreno', p: "Un guía que vive en Japón o en Perú, disponible durante toda la estancia y localizable fuera de las actividades." },
      { n: '03', t: 'Todo está incluido, también lo que apenas se ve', p: "Traslados, entradas, transportes internos, asistencia veinticuatro horas al día y seguro de cancelación." },
      { n: '04', t: 'Un viaje que se cuenta a la vuelta', p: "Los empleados vuelven con un cuaderno de viaje impreso, sus fotos y algo que contar durante meses." },
    ],
  },

  form: {
    eyebrow: 'CONTACTO',
    titre: 'Hablemos de su comité.',
    lede: "Rellene este formulario y le responderemos en dos días laborables con una propuesta de llamada y una primera estimación con cifras.",
    etape1: "La empresa",
    etape2: "La persona de contacto",
    etape3: 'El proyecto de viaje',
    raison: 'Razón social',
    raisonPh: 'Kiraku Industries SAS',
    siret: 'Número SIRET',
    siretPh: '123 456 789 00012',
    siretAide: 'Catorce cifras, sede o centro correspondiente.',
    taille: 'Empleados en el centro',
    adresse: 'Dirección',
    adressePh: "Empiece a escribir: 14 rue de l'Échiquier",
    adresseAide: 'Elija una sugerencia y el código postal y la ciudad se rellenan solos.',
    cp: 'Código postal',
    cpPh: '75010',
    cpCherche: 'Buscando el municipio…',
    cpVide: 'No se ha encontrado ningún municipio, escriba la ciudad.',
    cpAuto: 'La ciudad se rellena automáticamente.',
    ville: 'Ciudad',
    villePh: 'Paris',
    villeMultiple: 'Varios municipios comparten este código postal.',
    nom: 'Apellidos',
    nomPh: 'Aoyama',
    prenom: 'Nombre',
    prenomPh: 'Camille',
    email: 'Email',
    emailPh: 'camille@empresa.fr',
    poste: "Puesto en la empresa",
    postePh: 'Secretario del comité, representante, RR. HH.…',
    fixe: 'Teléfono fijo',
    fixePh: '01 42 33 12 90',
    mobile: 'Teléfono móvil',
    mobilePh: '06 45 78 21 09',
    mobileAide: 'Un móvil, francés o extranjero en formato +33 6 45 78 21 09.',
    destinations: 'Destinos que le interesan',
    dureeLabel: 'Duración prevista',
    saisonLabel: 'Temporada deseada',
    saisonAide: 'Puede elegir varias temporadas, le diremos cuál se presta mejor a un grupo.',
    contexte: 'Su contexto',
    contextePh: 'Número de salidas previstas, presupuesto por empleado, aportación del comité, calendario de su comunicación interna…',
    note: 'Respuesta en 48 h laborables. Sus datos se utilizan únicamente para este contacto.',
    tailles: ['De 0 a 250 empleados', 'De 250 a 599 empleados', 'De 600 a 999 empleados', '1.000 empleados o más'],
    pays: [
      { key: 'japon', label: 'Japón', sub: 'ocho itinerarios exclusivos' },
      { key: 'perou', label: 'Perú', sub: 'de los Andes al Machu Picchu, a pie y sin prisa' },
    ],
    durees: ['De 7 a 9 días', 'De 10 a 13 días', 'De 14 a 17 días', 'De 18 a 21 días o más'],
    saisons: [
      { key: 'hiver', label: 'Invierno', mois: 'dic · ene · feb' },
      { key: 'printemps', label: 'Primavera', mois: 'mar · abr · may' },
      { key: 'ete', label: 'Verano', mois: 'jun · jul · ago' },
      { key: 'automne', label: 'Otoño', mois: 'sept · oct · nov' },
    ],
    errRaison: 'La razón social es obligatoria.',
    errSiretRequis: 'El número SIRET es obligatorio.',
    errSiretFormat: 'El SIRET tiene catorce cifras.',
    errAdresse: "La dirección es obligatoria.",
    errCp: 'Un código postal de cinco cifras.',
    errVille: 'La ciudad es obligatoria.',
    errTaille: 'Indique una plantilla en el centro.',
    errPrenom: 'El nombre es obligatorio.',
    errNom: 'Los apellidos son obligatorios.',
    errPays: 'Elija al menos un destino.',
    merciTitre: (prenom) => `Tomamos nota, ${prenom}.`,
    merciDefautPrenom: 'gracias',
    merciTexte: (mobile, raison) => `Le responderemos en dos días laborables al ${mobile}, con una propuesta de horario y una primera estimación para ${raison}.`,
    merciDefautMobile: 'número indicado',
    merciDefautRaison: 'su comité',
    merciModifier: 'Modificar mi solicitud',
    merciParcourir: 'Ver los itinerarios',
  },
};
