// Page CSE, comites sociaux et economiques. Version francaise, reference des traductions.
export default {
  hero: {
    eyebrow: 'COMITÉS SOCIAUX ET ÉCONOMIQUES',
    titreAvant: 'Offrez à vos collaborateurs un voyage dont ils parleront ',
    titreBrush: 'longtemps',
    titreApres: '.',
    lede: "Kiraku Travel écrit des voyages au Japon pour des groupes de quatre à huit personnes. Nous travaillons avec les CSE qui cherchent autre chose qu'un catalogue, et qui veulent un interlocuteur au bout du fil.",
    cta1: 'Demander une mise en relation',
    cta2: 'Voir ce que nous apportons',
    photo: 'Ruelle de Kyoto au crépuscule',
  },

  intro: {
    eyebrow: 'LA MAISON',
    titre: 'Une petite agence, immatriculée, qui repère elle-même ses itinéraires.',
    p1: "Kiraku Travel est une agence indépendante basée à Paris, immatriculée Atout France sous le numéro IM075260052. Nous ne revendons pas des circuits achetés ailleurs : chaque itinéraire est repéré sur place, saison par saison, auberge par auberge.",
    p2: "Nos trois principes tiennent en peu de mots. Petits groupes, pour que le lieu reste vivant. Rythme lent, parce qu'un voyage se digère. Vérité des prix, tout est écrit avant de signer.",
    facts: [
      { n: '8', t: 'itinéraires signatures, de 7 à 22 jours' },
      { n: '4 à 8', t: 'voyageurs par départ en groupe' },
      { n: '48 h', t: 'pour une réponse ouvrée à votre demande' },
    ],
    photo: "Atelier d'artisan, repérage sur place",
  },

  apports: {
    eyebrow: 'CE QUE NOUS APPORTONS AU CSE',
    titre: 'Le comité garde la main, nous prenons la logistique.',
    items: [
      { n: '01', t: 'Une offre négociée, sans surcoût pour le CSE', p: "Des tarifs de groupe sur nos itinéraires signatures, avec la même prestation que nos voyageurs individuels. Aucun frais de dossier facturé au comité." },
      { n: '02', t: 'Un interlocuteur unique du premier échange au retour', p: "Une personne qui connaît votre dossier, joignable par téléphone, qui suit les inscriptions, les acomptes et les imprévus." },
      { n: '03', t: 'Des supports prêts à diffuser', p: "Affiches, fiches itinéraires, textes pour votre intranet et votre newsletter. Nous préparons la communication interne avec vous." },
      { n: '04', t: 'Une billetterie souple', p: "Départs échelonnés, paiement en plusieurs fois, participation du comité modulable par collaborateur ou par foyer." },
    ],
  },

  benefices: {
    eyebrow: 'LES BÉNÉFICES POUR VOS COLLABORATEURS',
    titre: "Un voyage qui ne ressemble pas à un voyage d'entreprise.",
    items: [
      { n: '01', t: 'Des groupes de quatre à huit personnes', p: "Jamais de car, jamais de fanion. Des trains, des auberges familiales, des tables où l'on s'assied avec les habitants." },
      { n: '02', t: 'Un accompagnement francophone sur place', p: "Un guide qui vit au Japon ou au Pérou, disponible pendant tout le séjour et joignable en dehors des activités." },
      { n: '03', t: 'Tout est inclus, y compris ce qui se voit peu', p: "Transferts, entrées, transports intérieurs, assistance vingt-quatre heures sur vingt-quatre et assurance annulation." },
      { n: '04', t: 'Un voyage qui se raconte au retour', p: "Les collaborateurs rentrent avec un carnet de voyage imprimé, leurs photos et de quoi en parler pendant des mois." },
    ],
  },

  form: {
    eyebrow: 'MISE EN RELATION',
    titre: 'Parlons de votre comité.',
    lede: "Remplissez ce formulaire, nous revenons vers vous sous deux jours ouvrés avec une proposition d'appel et une première estimation chiffrée.",
    etape1: "L'entreprise",
    etape2: "L'interlocuteur",
    etape3: 'Le projet de voyage',
    raison: 'Raison sociale',
    raisonPh: 'Kiraku Industries SAS',
    siret: 'Numéro SIRET',
    siretPh: '123 456 789 00012',
    siretAide: 'Quatorze chiffres, siège ou établissement concerné.',
    taille: 'Collaborateurs sur site',
    adresse: 'Adresse',
    adressePh: "Commencez à taper : 14 rue de l'Échiquier",
    adresseAide: 'Choisissez une suggestion, le code postal et la ville se remplissent.',
    cp: 'Code postal',
    cpPh: '75010',
    cpCherche: 'Recherche de la commune…',
    cpVide: 'Aucune commune trouvée, saisissez la ville.',
    cpAuto: 'La ville se remplit automatiquement.',
    ville: 'Ville',
    villePh: 'Paris',
    villeMultiple: 'Plusieurs communes partagent ce code postal.',
    nom: 'Nom',
    nomPh: 'Aoyama',
    prenom: 'Prénom',
    prenomPh: 'Camille',
    email: 'Email',
    emailPh: 'camille@entreprise.fr',
    poste: "Poste dans l'entreprise",
    postePh: 'Secrétaire du CSE, élu, RH…',
    fixe: 'Téléphone fixe',
    fixePh: '01 42 33 12 90',
    mobile: 'Téléphone portable',
    mobilePh: '06 45 78 21 09',
    mobileAide: 'Un mobile, français ou étranger au format +33 6 45 78 21 09.',
    destinations: 'Destinations qui vous intéressent',
    dureeLabel: 'Durée envisagée',
    saisonLabel: 'Saison voulue',
    saisonAide: 'Plusieurs saisons possibles, nous vous dirons ce qui se prête le mieux à un groupe.',
    contexte: 'Votre contexte',
    contextePh: 'Nombre de départs envisagés, budget par collaborateur, participation du comité, calendrier de votre communication interne…',
    note: 'Réponse sous 48 h ouvrées. Vos données servent uniquement à cet échange.',
    tailles: ['0 à 250 collaborateurs', '250 à 599 collaborateurs', '600 à 999 collaborateurs', '1 000 collaborateurs et plus'],
    pays: [
      { key: 'japon', label: 'Japon', sub: 'huit itinéraires signatures' },
      { key: 'perou', label: 'Pérou', sub: 'des Andes au Machu Picchu, à pied et sans hâte' },
    ],
    durees: ['7 à 9 jours', '10 à 13 jours', '14 à 17 jours', '18 à 21 jours et plus'],
    saisons: [
      { key: 'hiver', label: 'Hiver', mois: 'déc · janv · févr' },
      { key: 'printemps', label: 'Printemps', mois: 'mars · avr · mai' },
      { key: 'ete', label: 'Été', mois: 'juin · juil · août' },
      { key: 'automne', label: 'Automne', mois: 'sept · oct · nov' },
    ],
    errRaison: 'La raison sociale est requise.',
    errSiretRequis: 'Le numéro SIRET est requis.',
    errSiretFormat: 'Le SIRET compte quatorze chiffres.',
    errAdresse: "L'adresse est requise.",
    errCp: 'Un code postal à cinq chiffres.',
    errVille: 'La ville est requise.',
    errTaille: 'Indiquez un effectif sur site.',
    errPrenom: 'Le prénom est requis.',
    errNom: 'Le nom est requis.',
    errPays: 'Choisissez au moins une destination.',
    merciTitre: (prenom) => `C'est noté, ${prenom}.`,
    merciDefautPrenom: 'merci',
    merciTexte: (mobile, raison) => `Nous revenons vers vous sous deux jours ouvrés au ${mobile}, avec une proposition d'horaire et une première estimation pour ${raison}.`,
    merciDefautMobile: 'numéro indiqué',
    merciDefautRaison: 'votre comité',
    merciModifier: 'Modifier ma demande',
    merciParcourir: 'Parcourir les itinéraires',
  },
};
