// Works councils page. English version, translated from cse.fr.js.
export default {
  hero: {
    eyebrow: 'WORKS COUNCILS',
    titreAvant: 'Give your employees a trip they will still be talking about ',
    titreBrush: 'years from now',
    titreApres: '.',
    lede: "Kiraku Travel writes journeys to Japan for groups of four to eight people. We work with works councils looking for something other than a catalogue, and who want a real person at the end of the line.",
    cta1: 'Request an introduction',
    cta2: 'See what we bring',
    photo: 'A Kyoto lane at dusk',
  },

  intro: {
    eyebrow: 'THE AGENCY',
    titre: 'A small licensed agency that scouts its own itineraries.',
    p1: "Kiraku Travel is an independent agency based in Paris, registered with Atout France under number IM075260052. We do not resell tours bought elsewhere: every itinerary is scouted on the ground, season by season, inn by inn.",
    p2: "Our three principles take very few words. Small groups, so the place stays alive. A slow pace, because a journey needs time to settle. Honest pricing, everything is written down before you sign.",
    facts: [
      { n: '8', t: 'signature itineraries, from 7 to 22 days' },
      { n: '4 to 8', t: 'travellers per group departure' },
      { n: '48 h', t: 'to answer your enquiry, working days' },
    ],
    photo: "A craftsman's workshop, scouted on the ground",
  },

  apports: {
    eyebrow: 'WHAT WE BRING TO YOUR WORKS COUNCIL',
    titre: 'The committee keeps control, we take on the logistics.',
    items: [
      { n: '01', t: 'A negotiated offer, at no extra cost to the council', p: "Group rates on our signature itineraries, with exactly the same service as our individual travellers receive. No booking fee charged to the committee." },
      { n: '02', t: 'One contact from the first exchange to the return', p: "Someone who knows your file, reachable by telephone, who follows the sign ups, the deposits and the unexpected." },
      { n: '03', t: 'Materials ready to share', p: "Posters, itinerary sheets, copy for your intranet and your newsletter. We prepare the internal communication with you." },
      { n: '04', t: 'Flexible ticketing', p: "Staggered departures, payment in instalments, a council contribution that can be adjusted per employee or per household." },
    ],
  },

  benefices: {
    eyebrow: 'THE BENEFITS FOR YOUR EMPLOYEES',
    titre: "A trip that does not feel like a corporate trip.",
    items: [
      { n: '01', t: 'Groups of four to eight people', p: "Never a coach, never a flag. Trains, family run inns, tables where you sit down with local people." },
      { n: '02', t: 'An English speaking guide on the ground', p: "A guide who lives in Japan or in Peru, available throughout the stay and reachable outside the activities." },
      { n: '03', t: 'Everything is included, even what goes unnoticed', p: "Transfers, entrance fees, domestic transport, twenty four hour assistance and cancellation insurance." },
      { n: '04', t: 'A trip worth telling on the way home', p: "Employees come home with a printed travel journal, their photographs and plenty to talk about for months." },
    ],
  },

  form: {
    eyebrow: 'GET IN TOUCH',
    titre: 'Let us talk about your committee.',
    lede: "Fill in this form and we will come back to you within two working days with a proposed call and a first costed estimate.",
    etape1: "The company",
    etape2: "The contact",
    etape3: 'The travel project',
    raison: 'Registered company name',
    raisonPh: 'Kiraku Industries SAS',
    siret: 'SIRET number',
    siretPh: '123 456 789 00012',
    siretAide: 'Fourteen digits, head office or the site concerned.',
    taille: 'Employees on site',
    adresse: 'Address',
    adressePh: "Start typing: 14 rue de l'Échiquier",
    adresseAide: 'Pick a suggestion and the postcode and town fill in.',
    cp: 'Postcode',
    cpPh: '75010',
    cpCherche: 'Looking up the town…',
    cpVide: 'No town found, please type it in.',
    cpAuto: 'The town fills in automatically.',
    ville: 'Town',
    villePh: 'Paris',
    villeMultiple: 'Several towns share this postcode.',
    nom: 'Surname',
    nomPh: 'Aoyama',
    prenom: 'First name',
    prenomPh: 'Camille',
    email: 'Email',
    emailPh: 'camille@company.fr',
    poste: "Role in the company",
    postePh: 'Works council secretary, elected member, HR…',
    fixe: 'Landline',
    fixePh: '01 42 33 12 90',
    mobile: 'Mobile',
    mobilePh: '06 45 78 21 09',
    mobileAide: 'A mobile number, French or foreign in the format +33 6 45 78 21 09.',
    destinations: 'Destinations you are interested in',
    dureeLabel: 'Length of stay',
    saisonLabel: 'Preferred season',
    saisonAide: 'Several seasons are possible, we will tell you what suits a group best.',
    contexte: 'Your context',
    contextePh: 'Number of departures planned, budget per employee, council contribution, timing of your internal communication…',
    note: 'A reply within 48 working hours. Your data is used for this exchange only.',
    tailles: ['0 to 250 employees', '250 to 599 employees', '600 to 999 employees', '1,000 employees and more'],
    pays: [
      { key: 'japon', label: 'Japan', sub: 'eight signature itineraries' },
      { key: 'perou', label: 'Peru', sub: 'from the Andes to Machu Picchu, on foot and without haste' },
    ],
    durees: ['7 to 9 days', '10 to 13 days', '14 to 17 days', '18 to 21 days and more'],
    saisons: [
      { key: 'hiver', label: 'Winter', mois: 'Dec · Jan · Feb' },
      { key: 'printemps', label: 'Spring', mois: 'Mar · Apr · May' },
      { key: 'ete', label: 'Summer', mois: 'Jun · Jul · Aug' },
      { key: 'automne', label: 'Autumn', mois: 'Sep · Oct · Nov' },
    ],
    errRaison: 'The registered company name is required.',
    errSiretRequis: 'The SIRET number is required.',
    errSiretFormat: 'The SIRET has fourteen digits.',
    errAdresse: "The address is required.",
    errCp: 'A five digit postcode.',
    errVille: 'The town is required.',
    errTaille: 'Give a headcount on site.',
    errPrenom: 'The first name is required.',
    errNom: 'The surname is required.',
    errPays: 'Choose at least one destination.',
    merciTitre: (prenom) => `Noted, ${prenom}.`,
    merciDefautPrenom: 'thank you',
    merciTexte: (mobile, raison) => `We will come back to you within two working days on ${mobile}, with a proposed time and a first estimate for ${raison}.`,
    merciDefautMobile: 'the number given',
    merciDefautRaison: 'your committee',
    merciModifier: 'Edit my request',
    merciParcourir: 'Browse the itineraries',
  },
};
