// Incluido y no incluido en el precio, fichas practicas y pictogramas.
// Version espanola, traducida de la referencia francesa.
export default {
  inclusBase: [
    "La bienvenida personalizada en el aeropuerto y la asistencia de su asesor de habla hispana durante toda la estancia",
    "Todos los traslados entre aeropuertos, estaciones y alojamientos",
    "Los transportes interiores previstos en el programa, Shinkansen, líneas locales, autobuses y barcos, tasas incluidas",
    "Las entradas de todos los templos, santuarios, museos y jardines incluidos en el programa",
    "La asistencia de nuestro equipo en Japón, localizable las veinticuatro horas del día durante la estancia",
    "El cuaderno de viaje Kiraku entregado antes de la salida, mapas, léxico y direcciones verificadas",
  ],
  exclusBase: [
    "Los vuelos internacionales desde y hacia Francia, las tasas aéreas y los gastos de equipaje",
    "El seguro de viaje · cancelación, equipaje, gastos médicos y repatriación, muy recomendable",
    "Las comidas no mencionadas en el programa y las bebidas servidas fuera de las comidas incluidas",
    "El suplemento de habitación individual, según disponibilidad",
    "Las actividades opcionales y el tiempo libre que usted organice a su iniciativa",
    "Los gastos personales · lavandería, comunicaciones, artesanía y recuerdos",
    "Los gastos de expedición o de renovación del pasaporte",
  ],
  notePourboire: "Las propinas no son costumbre en Japón · no se prevé ninguna, no se espera ninguna",

  circuits: {
    'CL-01': {
      titre: 'Del Neón al Silencio · catorce días',
      inclus: [
        "13 noches en habitación doble · hotel de barrio en Tokio, ryokan familiar en el campo, dos noches en templo shukubo",
        "Los desayunos cada mañana, ocho almuerzos y diez cenas, entre ellos dos comidas shojin ryori preparadas por los monjes",
        "Un guía de habla hispana permanente desde Tokio hasta el valle, y ponentes locales en las jornadas de taller",
        "El Japan Rail Pass de catorce días en clase ordinaria, activado a su llegada",
        "La visita guiada del mercado de Toyosu a primera hora de la mañana, entrada y degustación incluidas",
        "El taller de caligrafía shodo, material incluido, y su primera obra para llevar",
        "La ceremonia del té en casa de una familia de Kanazawa, en grupo reducido",
        "El porteo del equipaje entre Tokio y el campo, usted solo lleva una bolsa ligera",
      ],
      exclus: [
        "Los trayectos en taxi durante sus medias jornadas libres en Tokio",
        "El suplemento de ryokan con baño privado, bajo petición",
      ],
      options: [
        "Habitación individual durante toda la estancia: 690 € por persona",
        "Noche adicional en Tokio antes o después del circuito: 145 € por persona en habitación doble, desayuno incluido",
        "Mejora a Green Car en los trayectos en Shinkansen: 320 € por persona",
      ],
    },
    'CL-02': {
      titre: 'Mil Escalones hacia el Norte · catorce días',
      inclus: [
        "13 noches en habitación doble · tres noches en templo shukubo en el monte Koya, ryokan de montaña, minshuku de pueblo",
        "La pensión completa desde la cena del día 1 hasta el desayuno del día 14, salvo dos cenas libres",
        "Un guía de habla hispana especializado en el sintoísmo y el budismo japonés, presente cada día",
        "Los oficios de la mañana en los templos, en presencia de los monjes",
        "Las etapas a pie del Kumano Kodo, con traslado del equipaje de etapa en etapa",
        "El ritual de purificación en Ise, acompañado por un sacerdote del santuario",
        "Las entradas y las tasas de sendero en todo el recorrido de peregrinación",
        "El bastón de peregrino y el cuaderno de sellos shuin entregados al inicio",
      ],
      exclus: [
        "Los sellos shuin adicionales recogidos fuera del programa, unos 300 yenes cada uno",
        "Las ofrendas personales en los templos y santuarios",
        "El alquiler de calzado de marcha, en destino",
      ],
      options: [
        "Habitación individual, salvo en los templos donde el alojamiento es compartido: 540 € por persona",
        "Etapa adicional en el Kumano Kodo, una noche y un guía: 260 € por persona",
        "Masaje shiatsu después de las etapas a pie: 70 € la sesión",
      ],
    },
    'CL-03': {
      titre: 'De los Templos a los Corales · catorce días',
      inclus: [
        "13 noches en habitación doble · ryokan en Kioto, hotel a pie de mar en Okinawa, dos noches en casa de huéspedes en Ishigaki",
        "Los desayunos, seis almuerzos y nueve cenas, entre ellos una comida de la cocina ryukyu en casa de una familia",
        "El vuelo interior de Osaka a Naha y el vuelo de Naha a Ishigaki, tasas incluidas",
        "Un guía de habla hispana en Kioto, y después un acompañante okinawense en las islas",
        "Dos salidas con aletas, gafas y tubo por los arrecifes, material y barco incluidos",
        "Los accesos a los onsen y a los baños de sus alojamientos, toalla incluida",
        "Dos sesiones de yoga al amanecer, frente al mar",
        "Los traslados en barco entre las islas Yaeyama",
      ],
      exclus: [
        "Los bautismos y las salidas de buceo con botella, con reserva a la llegada",
        "El alquiler de traje de neopreno integral fuera de la temporada cálida",
        "Las excursiones marítimas opcionales que se ofrecen en destino",
      ],
      options: [
        "Habitación individual durante toda la estancia: 620 € por persona",
        "Bautismo de buceo con monitor, dos inmersiones: 180 € por persona",
        "Noche adicional en Ishigaki: 130 € por persona en habitación doble, desayuno incluido",
      ],
    },
    'CL-04': {
      titre: 'El Primer Aliento · siete días',
      inclus: [
        "6 noches en habitación doble · hotel equivalente a 3 estrellas en Tokio y Kioto, una noche en ryokan tradicional",
        "Los desayunos cada mañana, tres almuerzos y cuatro cenas",
        "Un guía de habla hispana durante las cinco jornadas de visita",
        "El Japan Rail Pass de siete días en clase ordinaria",
        "El alquiler de un kimono durante una jornada en Kioto, vestido y peinado incluidos",
        "La iniciación a la ceremonia del té en una casa de Gion",
        "Las entradas del castillo de Nijo, del Kinkakuji y del santuario de Fushimi Inari",
        "El traslado de su equipaje entre Tokio y Kioto",
      ],
      exclus: [
        "Las dos medias jornadas libres, transportes y entradas en destino",
        "El suplemento de cena kaiseki en el ryokan, bajo petición",
      ],
      options: [
        "Habitación individual durante toda la estancia: 380 € por persona",
        "Cena kaiseki en el ryokan, nueve servicios: 120 € por persona",
        "Noche adicional en Tokio o Kioto: 135 € por persona en habitación doble, desayuno incluido",
      ],
    },
    'CL-05': {
      titre: 'El Corazón del Viejo Japón · siete días',
      inclus: [
        "6 noches en habitación doble · dos noches en machiya de Kioto, ryokan en Nara, minshuku en el valle de Iga",
        "Los desayunos, cuatro almuerzos y cinco cenas, entre ellas una comida de dojo compartida con los practicantes",
        "Un guía de habla hispana practicante de artes marciales, presente cada día",
        "Dos sesiones de iniciación en dojo · kendo y kyudo, préstamo del equipo incluido",
        "La demostración privada de iaido a cargo de un maestro de Kioto",
        "La visita al taller de un forjador de sables, con demostración de pulido",
        "Los transportes interiores en tren y en autobús en todo el recorrido",
        "El keikogi de práctica entregado al inicio",
      ],
      exclus: [
        "Las clases de práctica adicionales fuera de las dos sesiones previstas",
        "La compra de un bokken o de cualquier equipo personal",
      ],
      options: [
        "Habitación individual durante toda la estancia: 410 € por persona",
        "Sesión de práctica adicional en dojo, dos horas: 95 € por persona",
        "Jornada adicional en el valle de Iga: 240 € por persona, alojamiento y guía incluidos",
      ],
    },
    'CL-06': {
      titre: 'La Travesía sin Prisa · veintiún días',
      inclus: [
        "20 noches en habitación doble · hoteles de ciudad, ryokan de provincia, dos noches en una granja en explotación en Hokkaido",
        "La pensión completa desde la cena del día 1 hasta el desayuno del día 21, salvo tres cenas libres",
        "Un guía de habla hispana permanente durante los veintiún días",
        "El Japan Rail Pass de veintiún días en clase ordinaria, más el ferri a Hokkaido",
        "Cinco talleres de cocina · soba, ramen, pescado, fermentación y repostería wagashi",
        "Dos visitas guiadas de mercados de pescado, degustación incluida",
        "La visita a una fábrica de sake con degustación comentada por el maestro elaborador",
        "Dos cenas en casa de chefs, menú de temporada en grupo reducido",
        "El porteo del equipaje entre cada gran etapa",
      ],
      exclus: [
        "Las degustaciones de sake y de whisky japonés fuera del programa",
        "Las reservas de restaurantes gastronómicos durante sus veladas libres",
        "El suplemento de ryokan con baño privado, bajo petición",
      ],
      options: [
        "Habitación individual durante toda la estancia: 1.090 € por persona",
        "Menú degustación en un restaurante con estrella de Tokio, reserva incluida: 280 € por persona",
        "Mejora a Green Car en los trayectos en Shinkansen: 480 € por persona",
      ],
    },
    'CL-07': {
      titre: 'De las Torres a los Tejados de Paja · veintiún días',
      inclus: [
        "20 noches en habitación doble · hoteles en Tokio, Nagoya y Kanazawa, dos noches en gassho-zukuri en Shirakawa-go",
        "Los desayunos cada mañana, diez almuerzos y trece cenas",
        "Un guía de habla hispana permanente, y un acompañante especializado en las jornadas de animación",
        "El Japan Rail Pass de veintiún días en clase ordinaria",
        "Las entradas reservadas del museo Ghibli y del parque Ghibli, franjas horarias confirmadas antes de la salida",
        "Dos jornadas dedicadas a los barrios de la animación y del videojuego, Akihabara y Nakano",
        "La visita a un estudio de animación con encuentro con un animador, sujeta al calendario de producción",
        "El taller de dibujo manga con un autor, material incluido",
        "El porteo del equipaje entre cada gran etapa",
      ],
      exclus: [
        "Las compras en tienda, figuras, ediciones y artículos de merchandising",
        "Las partidas en los salones recreativos y en los karaokes",
        "Los eventos puntuales y las convenciones cuyas fechas no se conocen en el momento de la reserva",
      ],
      options: [
        "Habitación individual durante toda la estancia: 1.040 € por persona",
        "Jornada adicional en Tokio con su guía: 290 € por persona",
        "Sesión de fotos en cosplay, vestuario y retoques incluidos: 180 € por persona",
      ],
    },
    'CL-08': {
      titre: 'Hasta los Cedros Milenarios · veintidós días',
      inclus: [
        "21 noches en habitación doble · hoteles de ciudad, ryokan de montaña, tres noches en la isla de Yakushima",
        "La pensión completa desde la cena del día 1 hasta el desayuno del día 22, salvo cuatro cenas libres",
        "Un guía de habla hispana permanente, y un guía naturalista en Yakushima",
        "El Japan Rail Pass de veintiún días, más el vuelo interior a Kagoshima y el ferri a Yakushima",
        "Los dos días de marcha por el bosque primario hasta el cedro Jomon Sugi, permiso de sendero incluido",
        "Las entradas del museo Ghibli y de los lugares que inspiraron las películas",
        "Los accesos a los onsen de costa y de montaña, toalla incluida",
        "El alquiler del material de lluvia en Yakushima, capa y cubremochila",
        "El porteo del equipaje entre cada gran etapa",
      ],
      exclus: [
        "Las salidas adicionales al bosque con guía naturalista",
        "El alquiler de calzado de marcha y de bastones",
        "Las comidas para llevar durante las jornadas de senderismo libre",
      ],
      options: [
        "Habitación individual, salvo las noches en refugio: 1.120 € por persona",
        "Jornada de marcha adicional en Yakushima con guía naturalista: 210 € por persona",
        "Noche adicional en Kagoshima: 130 € por persona en habitación doble, desayuno incluido",
      ],
    },
    'CL-09': {
      titre: 'Tokio, Kioto y travesía de los Alpes · doce días',
      inclus: [
        "5 noches en hotel equivalente a 3 estrellas, habitación con dos camas individuales, en Tokio y en Kioto",
        "5 noches en refugio de montaña durante el trek, alojamiento en habitaciones y dormitorios colectivos, la última en el ryokan Yarimikan con acceso a los onsen",
        "La pensión completa del día 3 al día 11, desayuno, almuerzo y cena, con picnics incluidos en las etapas",
        "Un guía de habla hispana de alta montaña durante toda la estancia, y un guía de Tokio en la jornada en Tokio",
        "Los traslados en tren y en autocar del día 2 al día 12, entre ellos Tokio a Matsumoto y Kamikochi a Kioto",
        "La entrada del castillo de Matsumoto y los accesos de sendero de la vía Omote Ginza",
        "El porteo de su equipaje de Tokio hasta Kioto durante los seis días de trek",
        "Las tasas de refugio y las noches de montaña reservadas por adelantado",
      ],
      exclus: [
        "El material personal de montaña · calzado, saco de dormir ligero, bastones y ropa técnica",
        "La variante del día 6 hacia una cima adicional, acompañamiento incluido pero sujeta a la meteorología",
        "Las bebidas consumidas en el refugio fuera de las comidas",
      ],
      options: [
        "Habitación individual en hotel, según disponibilidad: 425 € por las 5 noches de la estancia, y después 75 € por noche adicional",
        "Noche adicional en Tokio o Kioto: 125 € por persona en habitación doble, desayuno incluido",
        "Noche adicional en habitación individual: 200 €",
        "Alquiler del saco de dormir ligero de refugio: 45 € por la estancia",
      ],
    },
    KUNISAKI: {
      titre: 'El sendero de Kunisaki · siete días',
      inclus: [
        "6 noches en minshuku familiares y en ryokan, en habitación doble",
        "La pensión completa desde la cena del día 1 hasta el desayuno del día 7, incluidas todas las cenas de familia",
        "Un guía de habla hispana permanente durante los siete días",
        "Todos los transportes locales, trenes de línea, autobuses de valle y traslados",
        "La jornada entera de tintura aizome con Tanaka-san, material y tela incluidos",
        "El almuerzo en casa del monje de Futagoji, durante la jornada de sendero",
        "La primera hora de la mañana en el mercado de Saiki, compra del almuerzo y preparación en sashimi incluidas",
        "La cena kaiseki de nueve servicios en el ryokan del monte Tsurumi",
      ],
      exclus: [
        "Los baños de barrio tomados fuera del programa, unos cientos de yenes la entrada",
        "Las tardes libres y las actividades que usted añada",
      ],
      options: [
        "Habitación individual, según disponibilidad: 350 € por persona",
        "Jornada de sendero adicional en la península: 190 € por persona",
        "Noche adicional en Fukuoka: 120 € por persona en habitación doble, desayuno incluido",
      ],
    },
  },

  fiches: {
    'CL-09': {
      hebergements: [
        "5 noches en hotel equivalente a 3 estrellas en Tokio y en Kioto, habitación con dos camas individuales",
        "5 noches en refugio de montaña durante el trek, alojamiento en habitaciones y dormitorios colectivos",
        "La última noche de trek en el ryokan Yarimikan, con acceso a los onsen",
        "Habitación individual en hotel posible, según disponibilidad y con suplemento",
        "Noche adicional en Tokio o en Kioto en opción, antes o después del circuito",
      ],
      transports: [
        "Todos los traslados entre aeropuertos, estaciones y alojamientos",
        "Tren de Tokio a Matsumoto, 2 h 30, y después carretera hasta Nakabusa onsen",
        "Autocar de Kamikōchi hasta Kioto el día 10",
        "Porteo de su equipaje de Tokio a Kioto durante los seis días de trek",
        "Vuelos internacionales no incluidos, le ayudamos a elegir los horarios",
      ],
      guide: [
        "Un guía de habla hispana de alta montaña durante toda la estancia",
        "Un guía de Tokio en la jornada de visita en Tokio",
        "Grupo reducido de 4 a 8 personas",
        "Asistencia de nuestro equipo en Japón, localizable las veinticuatro horas del día",
      ],
      equipement: [
        "Botas de senderismo de caña alta, ya usadas, de suela dentada",
        "Saco de dormir ligero de refugio, en alquiler con nosotros por 45 € la estancia",
        "Bastones de marcha, chaqueta impermeable y cortavientos",
        "Guantes y gorro ligero, las noches en altura siguen siendo frías en verano",
        "Mochila de 30 a 40 litros, el resto de su equipaje viaja hasta Kioto",
        "Linterna frontal y cantimplora de litro y medio",
      ],
    },
    KUNISAKI: {
      hebergements: [
        "6 noches en minshuku familiares y en ryokan, en habitación doble",
        "La noche del día 6 en el ryokan del monte Tsurumi, con baños y cena kaiseki",
        "Baños compartidos en la mayoría de los minshuku, fuera de la habitación",
        "Habitación individual según disponibilidad: 350 € por persona",
        "Noche adicional en Fukuoka en opción: 120 € por persona",
      ],
      transports: [
        "Recepción en la estación de Oita y todos los traslados de la estancia",
        "Trenes de línea local y autobuses de valle en toda la península",
        "Regreso a Fukuoka el último día",
        "Vuelos internacionales no incluidos, le ayudamos a elegir los horarios",
      ],
      guide: [
        "Un guía de habla hispana permanente durante los siete días",
        "Ponentes locales: Tanaka-san para el aizome, el monje de Futagoji",
        "De uno a ocho viajeros, sin ningún otro grupo",
        "Asistencia de nuestro equipo en Japón, localizable las veinticuatro horas del día",
      ],
      equipement: [
        "Calzado de marcha flexible, está prevista una jornada de treinta kilómetros",
        "Ropa de lluvia ligera, la temporada va de abril a junio",
        "Una toalla de aseo para los baños de barrio",
        "Una bolsa pequeña de día para los senderos de templos",
        "Una ropa que no le importe manchar para el taller de tintura",
      ],
    },
  },

  visuels: {
    'CL-09': [
      { ico: 'bed', lbl: 'Hoteles 3★ y refugios de montaña' },
      { ico: 'meal', lbl: 'Pensión completa, días 3 a 11' },
      { ico: 'guide', lbl: 'Guía de habla hispana de alta montaña' },
      { ico: 'train', lbl: 'Trenes y autocares interiores' },
      { ico: 'luggage', lbl: 'Porteo del equipaje de Tokio a Kioto' },
      { ico: 'mountain', lbl: 'Accesos de sendero, vía Omote Ginza' },
      { ico: 'ticket', lbl: 'Castillo de Matsumoto' },
      { ico: 'onsen', lbl: 'Onsen del ryokan Yarimikan' },
      { ico: 'flag', lbl: 'Cuaderno de viaje Kiraku' },
    ],
    KUNISAKI: [
      { ico: 'bed', lbl: 'Minshuku y ryokan, 6 noches' },
      { ico: 'meal', lbl: 'Pensión completa, todas las cenas de familia' },
      { ico: 'guide', lbl: 'Guía de habla hispana permanente' },
      { ico: 'train', lbl: 'Transportes locales y traslados' },
      { ico: 'flag', lbl: 'Taller aizome, una jornada entera' },
      { ico: 'temple', lbl: 'Almuerzo en casa del monje de Futagoji' },
      { ico: 'market', lbl: 'Mercado de Saiki a primera hora de la mañana' },
      { ico: 'onsen', lbl: 'Baños del ryokan del monte Tsurumi' },
      { ico: 'ticket', lbl: 'Cuaderno de viaje Kiraku' },
    ],
  },
};
