// What is included and not included in the price, practical sheets and pictograms.
// English version, translated from the French reference.
export default {
  inclusBase: [
    "The personalised welcome at the airport and the assistance of your English speaking adviser throughout the stay",
    "All transfers between airports, stations and accommodation",
    "The domestic transport set out in the programme, Shinkansen, local lines, buses and boats, taxes included",
    "The entrance fees for every temple, shrine, museum and garden listed in the programme",
    "The assistance of our team in Japan, reachable twenty four hours a day during the stay",
    "The Kiraku travel notebook handed over before departure, maps, glossary and checked addresses",
  ],
  exclusBase: [
    "International flights to and from France, airline taxes and baggage charges",
    "Travel insurance · cancellation, baggage, medical costs and repatriation, strongly recommended",
    "Meals not mentioned in the programme and drinks served outside the included meals",
    "The single room supplement, subject to availability",
    "Optional activities and the free time left to your own initiative",
    "Personal expenses · laundry, communications, crafts and souvenirs",
    "Passport issue or renewal fees",
  ],
  notePourboire: "Tipping is not customary in Japan · none is planned, none is expected",

  circuits: {
    'CL-01': {
      titre: 'From Neon to Silence · fourteen days',
      inclus: [
        "13 nights in a double room · neighbourhood hotel in Tokyo, family run ryokan in the countryside, two nights in a shukubo temple",
        "Breakfast every morning, eight lunches and ten dinners, including two shojin ryori meals prepared by the monks",
        "A permanent English speaking guide from Tokyo to the valley, and local hosts on the workshop days",
        "The fourteen day Japan Rail Pass in ordinary class, activated on your arrival",
        "The guided visit of Toyosu market in the early morning, entrance and tasting included",
        "The shodo calligraphy workshop, materials provided, and your first work to take home",
        "The tea ceremony with a Kanazawa family, in a small group",
        "The transport of your luggage between Tokyo and the countryside, you keep only a light bag",
      ],
      exclus: [
        "Taxi journeys during your free half days in Tokyo",
        "The supplement for a ryokan with a private bath, on request",
      ],
      options: [
        "Single room for the whole stay: 690 € per person",
        "Extra night in Tokyo before or after the tour: 145 € per person in a double room, breakfast included",
        "Green Car upgrade on the Shinkansen journeys: 320 € per person",
      ],
    },
    'CL-02': {
      titre: 'A Thousand Steps North · fourteen days',
      inclus: [
        "13 nights in a double room · three nights in a shukubo temple on Mount Koya, mountain ryokan, village minshuku",
        "Full board from dinner on day 1 to breakfast on day 14, apart from two free dinners",
        "An English speaking guide specialising in Shinto and Japanese Buddhism, present every day",
        "The morning services in the temples, in the presence of the monks",
        "The walked stages of the Kumano Kodo, with luggage transfer from stage to stage",
        "The purification ritual at Ise, accompanied by a priest of the shrine",
        "The entrance fees and trail taxes over the whole pilgrimage route",
        "The pilgrim staff and the shuin stamp book handed over at the start",
      ],
      exclus: [
        "Additional shuin stamps collected outside the programme, around 300 yen each",
        "Personal offerings in the temples and shrines",
        "Walking shoe hire, on site",
      ],
      options: [
        "Single room, apart from the temples where the sleeping quarters are shared: 540 € per person",
        "Additional stage on the Kumano Kodo, one night and a guide: 260 € per person",
        "Shiatsu massage after the walked stages: 70 € per session",
      ],
    },
    'CL-03': {
      titre: 'From Temples to Coral · fourteen days',
      inclus: [
        "13 nights in a double room · ryokan in Kyoto, seaside hotel in Okinawa, two nights in a guest house on Ishigaki",
        "Breakfasts, six lunches and nine dinners, including a Ryukyu cuisine meal with a family",
        "The domestic flight from Osaka to Naha and the flight from Naha to Ishigaki, taxes included",
        "An English speaking guide in Kyoto, then an Okinawan escort on the islands",
        "Two snorkelling outings on the reefs, equipment and boat included",
        "Access to the onsen and to the baths of your accommodation, towel provided",
        "Two yoga sessions at daybreak, facing the sea",
        "The boat transfers between the Yaeyama islands",
      ],
      exclus: [
        "Introductory dives and scuba diving outings, to be booked on arrival",
        "Full wetsuit hire outside the warm season",
        "The optional sea excursions offered on site",
      ],
      options: [
        "Single room for the whole stay: 620 € per person",
        "Supervised introductory dive, two immersions: 180 € per person",
        "Extra night on Ishigaki: 130 € per person in a double room, breakfast included",
      ],
    },
    'CL-04': {
      titre: 'The First Breath · seven days',
      inclus: [
        "6 nights in a double room · 3 star equivalent hotel in Tokyo and Kyoto, one night in a traditional ryokan",
        "Breakfast every morning, three lunches and four dinners",
        "An English speaking guide on the five days of visits",
        "The seven day Japan Rail Pass in ordinary class",
        "The hire of a kimono for a day in Kyoto, dressing and hairstyling included",
        "The introduction to the tea ceremony in a house in Gion",
        "The entrance fees for Nijo castle, Kinkakuji and Fushimi Inari shrine",
        "The transport of your luggage between Tokyo and Kyoto",
      ],
      exclus: [
        "The two free half days, transport and entrance fees on site",
        "The kaiseki dinner supplement at the ryokan, on request",
      ],
      options: [
        "Single room for the whole stay: 380 € per person",
        "Kaiseki dinner at the ryokan, nine courses: 120 € per person",
        "Extra night in Tokyo or Kyoto: 135 € per person in a double room, breakfast included",
      ],
    },
    'CL-05': {
      titre: 'The Heart of Old Japan · seven days',
      inclus: [
        "6 nights in a double room · two nights in a Kyoto machiya, ryokan in Nara, minshuku in the Iga valley",
        "Breakfasts, four lunches and five dinners, including a dojo meal shared with the practitioners",
        "An English speaking guide who practises the martial arts, present every day",
        "Two introductory sessions in a dojo · kendo and kyudo, loan of the equipment included",
        "The private iaido demonstration by a master from Kyoto",
        "The visit to the workshop of a swordsmith, with a polishing demonstration",
        "The domestic transport by train and bus over the whole route",
        "The practice keikogi handed over at the start",
      ],
      exclus: [
        "Additional practice classes beyond the two planned sessions",
        "The purchase of a bokken or of any personal equipment",
      ],
      options: [
        "Single room for the whole stay: 410 € per person",
        "Additional practice session in a dojo, two hours: 95 € per person",
        "Additional day in the Iga valley: 240 € per person, accommodation and guide included",
      ],
    },
    'CL-06': {
      titre: 'The Unhurried Crossing · twenty one days',
      inclus: [
        "20 nights in a double room · city hotels, provincial ryokan, two nights on a working farm in Hokkaido",
        "Full board from dinner on day 1 to breakfast on day 21, apart from three free dinners",
        "A permanent English speaking guide over the twenty one days",
        "The twenty one day Japan Rail Pass in ordinary class, plus the ferry to Hokkaido",
        "Five cooking workshops · soba, ramen, fish, fermentation and wagashi confectionery",
        "Two guided visits to fish markets, tasting included",
        "The visit to a sake brewery with a tasting presented by the master brewer",
        "Two dinners with chefs, seasonal menu in a small group",
        "The transport of your luggage between each main stage",
      ],
      exclus: [
        "Sake and Japanese whisky tastings outside the programme",
        "Bookings at fine dining restaurants during your free evenings",
        "The supplement for a ryokan with a private bath, on request",
      ],
      options: [
        "Single room for the whole stay: 1,090 € per person",
        "Tasting menu in a starred restaurant in Tokyo, booking included: 280 € per person",
        "Green Car upgrade on the Shinkansen journeys: 480 € per person",
      ],
    },
    'CL-07': {
      titre: 'From Towers to Thatched Roofs · twenty one days',
      inclus: [
        "20 nights in a double room · hotels in Tokyo, Nagoya and Kanazawa, two nights in a gassho-zukuri house in Shirakawa-go",
        "Breakfast every morning, ten lunches and thirteen dinners",
        "A permanent English speaking guide, and a specialist escort on the animation days",
        "The twenty one day Japan Rail Pass in ordinary class",
        "The reserved entrance to the Ghibli Museum and Ghibli Park, time slots confirmed before departure",
        "Two days devoted to the animation and gaming districts, Akihabara and Nakano",
        "The visit to an animation studio with a meeting with an animator, subject to the production schedule",
        "The manga drawing workshop with an author, materials provided",
        "The transport of your luggage between each main stage",
      ],
      exclus: [
        "Purchases in the shops, figurines, editions and goods",
        "Games played in the arcades and the karaoke rooms",
        "One off events and conventions whose dates are not known at the time of booking",
      ],
      options: [
        "Single room for the whole stay: 1,040 € per person",
        "Additional day in Tokyo with your guide: 290 € per person",
        "Cosplay photo session, costume and retouching included: 180 € per person",
      ],
    },
    'CL-08': {
      titre: 'To the Thousand Year Cedars · twenty two days',
      inclus: [
        "21 nights in a double room · city hotels, mountain ryokan, three nights on the island of Yakushima",
        "Full board from dinner on day 1 to breakfast on day 22, apart from four free dinners",
        "A permanent English speaking guide, and a naturalist guide on Yakushima",
        "The twenty one day Japan Rail Pass, plus the domestic flight to Kagoshima and the ferry to Yakushima",
        "The two days of walking in primary forest up to the Jomon Sugi cedar, trail permit included",
        "The entrance fees for the Ghibli Museum and for the places that inspired the films",
        "Access to the seaside and mountain onsen, towel provided",
        "The hire of rain gear on Yakushima, cape and rucksack cover",
        "The transport of your luggage between each main stage",
      ],
      exclus: [
        "Additional forest outings with a naturalist guide",
        "The hire of walking shoes and poles",
        "Packed meals taken on the free hiking days",
      ],
      options: [
        "Single room, apart from the nights in mountain huts: 1,120 € per person",
        "Additional day of walking on Yakushima with a naturalist guide: 210 € per person",
        "Extra night in Kagoshima: 130 € per person in a double room, breakfast included",
      ],
    },
    'CL-09': {
      titre: 'Tokyo, Kyoto and the Alps traverse · twelve days',
      inclus: [
        "5 nights in a 3 star equivalent hotel, twin room, in Tokyo and in Kyoto",
        "5 nights in mountain huts during the trek, sleeping in rooms and shared dormitories, the last one at the Yarimikan ryokan with access to the onsen",
        "Full board from day 3 to day 11, breakfast, lunch and dinner, packed lunches included on the walking stages",
        "An English speaking high mountain guide for the whole stay, and a Tokyo guide on the day in Tokyo",
        "The train and coach transfers from day 2 to day 12, including Tokyo to Matsumoto and Kamikochi to Kyoto",
        "The entrance to Matsumoto castle and the trail access on the Omote Ginza route",
        "The transport of your luggage from Tokyo to Kyoto during the six days of trekking",
        "The mountain hut taxes and the mountain nights booked in advance",
      ],
      exclus: [
        "Personal mountain equipment · boots, lightweight sleeping bag, poles and technical clothing",
        "The day 6 variant towards an additional summit, supervision included but subject to the weather",
        "Drinks taken in the mountain huts outside meals",
      ],
      options: [
        "Single room in a hotel, subject to availability: 425 € for the 5 nights of the stay, then 75 € per additional night",
        "Extra night in Tokyo or Kyoto: 125 € per person in a double room, breakfast included",
        "Additional night in a single room: 200 €",
        "Hire of the lightweight mountain hut sleeping bag: 45 € for the stay",
      ],
    },
    KUNISAKI: {
      titre: 'The Kunisaki trail · seven days',
      inclus: [
        "6 nights in family run minshuku and in ryokan, in a double room",
        "Full board from dinner on day 1 to breakfast on day 7, including every family dinner",
        "A permanent English speaking guide over the seven days",
        "All the local transport, line trains, valley buses and transfers",
        "The full day of aizome dyeing with Tanaka-san, materials and fabric included",
        "Lunch with the monk of Futagoji, on the trail day",
        "The early morning at Saiki market, buying the lunch and its preparation as sashimi included",
        "The nine course kaiseki dinner at the ryokan on Mount Tsurumi",
      ],
      exclus: [
        "Neighbourhood baths taken outside the programme, a few hundred yen for entry",
        "The free afternoons and the activities you add to them",
      ],
      options: [
        "Single room, subject to availability: 350 € per person",
        "Additional trail day on the peninsula: 190 € per person",
        "Extra night in Fukuoka: 120 € per person in a double room, breakfast included",
      ],
    },
  },

  fiches: {
    'CL-09': {
      hebergements: [
        "5 nights in a 3 star equivalent hotel in Tokyo and in Kyoto, twin room",
        "5 nights in mountain huts during the trek, sleeping in rooms and shared dormitories",
        "The last night of the trek at the Yarimikan ryokan, with access to the onsen",
        "A single room in a hotel is possible, subject to availability and with a supplement",
        "Extra night in Tokyo or in Kyoto as an option, before or after the tour",
      ],
      transports: [
        "All transfers between airports, stations and accommodation",
        "Train from Tokyo to Matsumoto, 2 hr 30, then by road to Nakabusa onsen",
        "Coach from Kamikōchi to Kyoto on day 10",
        "Transport of your luggage from Tokyo to Kyoto during the six days of trekking",
        "International flights not included, we help you choose the times",
      ],
      guide: [
        "An English speaking high mountain guide for the whole stay",
        "A Tokyo guide on the day of visits in Tokyo",
        "Small group of 4 to 8 people",
        "Assistance from our team in Japan, reachable twenty four hours a day",
      ],
      equipement: [
        "High cut walking boots, broken in, with a lugged sole",
        "Lightweight mountain hut sleeping bag, hired from us for 45 € for the stay",
        "Walking poles, waterproof jacket and windproof top",
        "Gloves and a light hat, the nights at altitude stay cold in summer",
        "A 30 to 40 litre rucksack, the rest of your luggage travels on to Kyoto",
        "Head torch and a one and a half litre water bottle",
      ],
    },
    KUNISAKI: {
      hebergements: [
        "6 nights in family run minshuku and in ryokan, in a double room",
        "The night of day 6 at the ryokan on Mount Tsurumi, with baths and a kaiseki dinner",
        "Shared bathrooms in most of the minshuku, outside the bedroom",
        "Single room subject to availability: 350 € per person",
        "Extra night in Fukuoka as an option: 120 € per person",
      ],
      transports: [
        "Welcome at Oita station and all the transfers of the stay",
        "Local line trains and valley buses across the whole peninsula",
        "Return to Fukuoka on the last day",
        "International flights not included, we help you choose the times",
      ],
      guide: [
        "A permanent English speaking guide over the seven days",
        "Local hosts: Tanaka-san for the aizome, the monk of Futagoji",
        "From one to eight travellers, with no other group",
        "Assistance from our team in Japan, reachable twenty four hours a day",
      ],
      equipement: [
        "Soft walking shoes, one day of thirty kilometres is planned",
        "Light rainwear, the season runs from April to June",
        "A towel for the neighbourhood baths",
        "A small day bag for the temple trails",
        "Clothing you do not mind staining for the dyeing workshop",
      ],
    },
  },

  visuels: {
    'CL-09': [
      { ico: 'bed', lbl: '3★ hotels and mountain huts' },
      { ico: 'meal', lbl: 'Full board, days 3 to 11' },
      { ico: 'guide', lbl: 'English speaking high mountain guide' },
      { ico: 'train', lbl: 'Domestic trains and coaches' },
      { ico: 'luggage', lbl: 'Luggage transport from Tokyo to Kyoto' },
      { ico: 'mountain', lbl: 'Trail access, Omote Ginza route' },
      { ico: 'ticket', lbl: 'Matsumoto castle' },
      { ico: 'onsen', lbl: 'Onsen of the Yarimikan ryokan' },
      { ico: 'flag', lbl: 'Kiraku travel notebook' },
    ],
    KUNISAKI: [
      { ico: 'bed', lbl: 'Minshuku and ryokan, 6 nights' },
      { ico: 'meal', lbl: 'Full board, every family dinner' },
      { ico: 'guide', lbl: 'Permanent English speaking guide' },
      { ico: 'train', lbl: 'Local transport and transfers' },
      { ico: 'flag', lbl: 'Aizome workshop, a full day' },
      { ico: 'temple', lbl: 'Lunch with the monk of Futagoji' },
      { ico: 'market', lbl: 'Saiki market in the early morning' },
      { ico: 'onsen', lbl: 'Baths of the ryokan on Mount Tsurumi' },
      { ico: 'ticket', lbl: 'Kiraku travel notebook' },
    ],
  },
};
