// Itineraries: cards, index page, Kunisaki and Japanese Alps pages.
// English version, translated from the French reference.
export default {
  circuitsLong: {
    'CL-01': { title: 'From Neon to Silence', duree: '14 days / 13 nights', ribbon: 'Culture' },
    'CL-02': { title: 'A Thousand Steps North', duree: '14 days / 13 nights', ribbon: 'Spiritual' },
    'CL-03': { title: 'From Temples to Coral', duree: '14 days / 13 nights', ribbon: 'Wellbeing' },
    'CL-04': { title: 'The First Breath', duree: '7 days / 6 nights', ribbon: 'Culture' },
    'CL-05': { title: 'The Heart of Old Japan', duree: '7 days / 6 nights', ribbon: 'Martial Arts' },
    'CL-06': { title: 'The Unhurried Crossing', duree: '21 days / 20 nights', ribbon: 'Food' },
    'CL-07': { title: 'From Towers to Thatched Roofs', duree: '21 days / 20 nights', ribbon: 'Anime & Manga' },
    'CL-08': { title: 'To the Thousand Year Cedars', duree: '22 days / 21 nights', ribbon: 'Miyazaki' },
    'CL-09': { title: 'Tokyo, Kyoto and a southern traverse of the Japanese Alps', duree: '12 days / 11 nights', ribbon: 'Hiking', privateNote: '4 to 8 in a small group' },
  },

  circuitsCourts: {
    'CT-01': { title: 'Neon Tokyo', zone: 'Shinjuku, Harajuku, Shibuya', intensite: 'Brisk' },
    'CT-02': { title: 'Edo Tokyo', zone: 'Asakusa, Ueno, Akihabara', intensite: 'Moderate' },
    'CT-03': { title: 'Tokyo of Heights and Bay', zone: 'Asakusa, Skytree, Odaiba', intensite: 'Moderate' },
    'CT-04': { title: 'Literary Tokyo', zone: 'Ueno, Akihabara, Kanda, Jimbocho', intensite: 'Moderate' },
    'CT-05': { title: 'Tokyo of Panoramas', zone: 'Shinjuku, Roppongi, Daimon', intensite: 'Moderate' },
    'CT-06': { title: 'Tokyo of the Imagination', zone: 'Ghibli, Kichijoji, Koenji, Nakano', intensite: 'Gentle' },
    'CT-07': { title: 'Yokohama, Gateway to the Open Sea', zone: 'Kanagawa', intensite: 'Gentle' },
    'CT-08': { title: 'Enoshima and Kamakura', zone: 'Kanagawa', intensite: 'Brisk' },
    'CT-09': { title: 'Takaosan, the Mountain of the Tengu', zone: 'West Tokyo', intensite: 'Demanding' },
    'CT-10': { title: 'Nikko, the Shrine in the Cedars', zone: 'Tochigi', intensite: 'Moderate to demanding' },
    'CT-11': { title: 'Central Kyoto', zone: 'Imperial Palace, Nishiki, Gion', intensite: 'Gentle' },
    'CT-12': { title: "East Kyoto, the Philosopher's Path", zone: 'North Higashiyama', intensite: 'Brisk' },
    'CT-13': { title: 'North Kyoto', zone: 'Arashiyama, Hozugawa, Kinkakuji', intensite: 'Moderate' },
    'CT-14': { title: 'Kyoto, the Ten Thousand Torii', zone: 'Fushimi Inari, South Higashiyama', intensite: 'Demanding' },
    'CT-15': { title: 'Osaka, the City that Eats', zone: 'Umeda, Osaka Castle', intensite: 'Gentle' },
    'CT-16': { title: 'Downtown Osaka', zone: 'Shinsekai, Shitennoji, Namba, Dotonbori', intensite: 'Moderate' },
    'EX-01': { title: 'A Ryukyu Summer', zone: 'Extension', intensite: '5 days / 4 nights' },
  },

  index: {
    eyebrow: 'OUR LONG ITINERARIES',
    titre: 'Nine itineraries, from seven to twenty-two days.',
    kicker: '· each one rewoven around you.',
    droite: "No imposed dates on a private journey: you leave when you wish, for as long as you wish. From one to eight travellers privately, from four to eight in a small group.",
    courtsEyebrow: 'SHORT ITINERARIES',
    courtsTitre: 'Sixteen one-day modules.',
    courtsKicker: '· without accommodation or long-distance travel.',
    courtsDroite: "Extensions, stopovers, or building blocks for a tailor-made itinerary. Plus a five-day extension.",
    thRef: 'Ref',
    thNom: 'Name',
    thZone: 'Area',
    thIntensite: 'Intensity',
    bouton: 'Book a thirty-minute call',
    note: "You tell us what appeals to you. We tell you whether it is the right season.",
  },

  carrousels: {
    'CL-09': ['Tokyo and Fuji, at the start', 'The ridge, above 2,500 metres', 'The climb through the forest to Enzanso', 'Kyoto, at the finish'],
    KUNISAKI: ['The Futagoji trail', 'Aizome dyeing with Tanaka-san', 'A neighbourhood onsen in Beppu', 'The fish market in Saiki'],
  },

  kunisaki: {
    fil: 'Kunisaki, seven days',
    eyebrow: 'AN EXPERIENCE · KYUSHU',
    titre: 'Seven days on the Kunisaki trail.',
    ledeAvant: "The forgotten peninsula of Kyushu, its Tendai temples hidden in the forest, a whole day of ",
    ledeItalique: 'aizome',
    ledeApres: " dyeing with Tanaka-san, and a secret onsen in Beppu, the one where you pay 200 yen to a lady.",
    detailTitre: 'Seven mornings, seven dinners.',
    prix: '3 980 €',
    prixSub: 'per traveller, based on a double room · flights not included',
    recap: "Oita · Futagoji trail · aizome workshop with Tanaka-san · neighbourhood onsen in Beppu · Saiki market · Mount Tsurumi · Fukuoka",
    note: "International flights are not included; we help you book them at the best times. The season runs from April to June, the peninsula being at its finest before the rains. A slow journey, through a peninsula that the classic tours ignore. You sleep in minshuku and ryokan, you eat what was caught that morning, and you walk temple trails that few travellers ever take.",
    plus: [
      "A peninsula that the classic tours ignore, with no other group on the trails",
      "Six nights in minshuku and ryokan, every dinner included",
      "A whole day of aizome dyeing with Tanaka-san, and you leave with your own cloth",
      "The Saiki fish market at first light, lunch chosen and prepared on the spot",
      "A neighbourhood onsen in Beppu, the one where you pay 200 yen to the lady at the door",
      "From one to eight travellers, on the date of your choosing, with no imposed departures",
    ],
    facts: [
      { lbl: 'Departures', val: 'On the date of your choosing' },
      { lbl: 'Duration', val: '7 days / 6 nights' },
      { lbl: 'Level', val: 'Gentle walking' },
      { lbl: 'Travellers', val: '1 to 8 people' },
      { lbl: 'Board', val: 'Full board, except free afternoons' },
      { lbl: 'Accommodation', val: 'Minshuku and ryokan' },
    ],
    jours: [
      { n: 1, title: 'Arrival in Oita, dinner with Mariko-san', body: "Direct flight Paris → Tokyo, then the Shinkansen to Kokura, then a local line. We meet you at the station with a thermos. Family dinner at the minshuku, grilled fish, local rice, and a long bath.", tags: ['Local train', 'Minshuku', 'Home cooking'] },
      { n: 2, title: 'First trail: Futagoji', body: "Thirty kilometres on foot through the Tendai temples hidden in the forest. We walk slowly. Midday break with a monk who makes his own nattō.", tags: ['Hiking', 'Temple', 'Lunch at the temple'] },
      { n: 3, title: 'Aizome dyeing workshop with Tanaka-san', body: "A whole day learning indigo dyeing. Tanaka-san is 78, has no internet, and will let you leave with your own cloth, dried in the wind.", tags: ['Craft', 'A whole day'] },
      { n: 4, title: 'Secret onsen in Beppu, the local version', body: "Not the onsen from the guidebook. A small neighbourhood bath where you pay 200 yen to a lady who hands you a towel. A nap in the afternoon, izakaya dinner in the evening.", tags: ['Onsen', 'Izakaya'] },
      { n: 5, title: 'The Saiki fish market', body: "Up at 5 am. We cross paths with the fishermen coming in, we choose lunch on the spot, and a cook prepares it for us as sashimi at 10 in the morning. Free afternoon.", tags: ['Market', 'Meal'] },
      { n: 6, title: 'Forest bathing on Mount Tsurumi', body: "Gentle walking, six hours, a meditation break in a clearing. Evening meal at the ryokan, seasonal kaiseki, nine small dishes prepared by the owner.", tags: ['Gentle walking', 'Kaiseki'] },
      { n: 7, title: 'Back to Fukuoka, a last kissaten', body: "We make our way quietly back to Fukuoka. A last coffee in a prewar kissaten run by the same gentleman for 47 years, and that is that.", tags: ['Kissaten', 'Return'] },
    ],
  },

  alpes: {
    fil: 'Japanese Alps, twelve days',
    eyebrow: 'LONG ITINERARY · CL-09 · HIKING',
    titre: 'Tokyo, Kyoto and a southern traverse of the Japanese Alps',
    lede: "A southern traverse of the Northern Alps, in five stages along the Omote Ginza route, with the ascent of a summit above 3,000 metres. Five days of high mountain walking above 2,500 metres, framed by Tokyo at the start and Kyoto at the finish.",
    detailTitre: 'Twelve days, six of them in the mountains.',
    detailKicker: '· the trek fills days 5 to 10.',
    prix: '3 990 €',
    prixSub: 'per person, based on a twin room · flights and transfer not included',
    recap: "Tokyo, 3 days · Matsumoto · Nakabusa onsen · Enzanso, Tsubakuro and Jōnen huts · Omote Ginza route · summit at 3,000 m · Yarimikan ryokan · Kamikōchi · Kyoto, 2 days",
    note: "International flights are not included; we help you book them at the best times. The itinerary runs only in August and September, the high trails being passable in summer alone. The trek spends five days above 2,500 metres, carrying a light pack yourself: your luggage travels from Tokyo to Kyoto while you walk. Good physical condition and some experience of mid-mountain walking are necessary.",
    plus: [
      "Five days of high mountain walking above 2,500 metres, along the Omote Ginza route",
      "The ascent of a summit above 3,000 metres, with a lightened pack and a first light start",
      "A small group of 4 to 8 people, led by an English-speaking high mountain guide",
      "Your luggage travels from Tokyo to Kyoto while you walk, so you carry only what you need",
      "A night at the Yarimikan ryokan and its onsen, after the descent to the valley",
      "Tokyo at the start and Kyoto at the finish, with a guide in each of the two cities",
    ],
    facts: [
      { lbl: 'Next departure', val: '27 Sept 2026' },
      { lbl: 'Duration', val: '12 days / 11 nights' },
      { lbl: 'Level', val: 'Experienced · 5 to 7 hrs of walking' },
      { lbl: 'Group', val: '4 to 8 people' },
      { lbl: 'Board', val: 'Full board, days 3 to 11' },
      { lbl: 'Accommodation', val: '3★ hotels and mountain huts' },
    ],
    departs: [
      { du: '27 September 2026', au: '8 October 2026', prix: '3,990.00 €' },
      { du: '1 August 2027', au: '12 August 2027', prix: '4,250.00 €' },
      { du: '26 September 2027', au: '7 October 2027', prix: '4,250.00 €' },
    ],
    jours: [
      { n: 1, title: 'Flight to Tokyo', body: "Departure from France. Flight to Tokyo, meals and night on board according to your airline's schedule.", tags: ['Flight'] },
      { n: 2, title: 'Arrival in Tokyo', body: "Welcome at the airport, transfer and check in at the hotel. The rest of the day is free, time to let the jet lag settle.", tags: ['Transfer', 'Hotel'] },
      { n: 3, title: 'Tokyo with your guide', body: "A day in the capital with your Tokyo guide, from the great shrines to the districts that never sleep. Breakfast, lunch and dinner included.", tags: ['City', 'English-speaking guide'] },
      { n: 4, title: 'Tokyo, Matsumoto and Nakabusa onsen', body: "You leave your luggage at the hotel and keep only your trekking kit for days 5 to 10: you will find it again in Kyoto. Train to Matsumoto (2 hrs 30), a visit to the castle, then the road to Nakabusa onsen (1 hr), the starting point of the trek. Night at the Ariake hut.", tags: ['Train', 'Matsumoto Castle', 'Mountain hut'] },
      { n: 5, title: 'Climb to the Enzanso hut and Mount Tsubakuro', body: "The traverse begins with a steady climb through the forest to the Enzanso hut. The first panoramas open onto the alpine ranges. After a pause at the hut, you carry on to Mount Tsubakuro and its strangely shaped granite rocks.", tags: ['Forest climb', 'Panorama', 'Mountain hut'] },
      { n: 6, title: 'On the ridge, towards Mount Jōnen', body: "A day on the ridge above 2,500 metres. A colony of macaques has settled at the foot of Mount Jōnen: with a little patience, you will come across them. For those who wish to go further, a variant adds a summit to the stage.", tags: ['Ridge', 'Wildlife', 'Mountain hut'] },
      { n: 7, title: 'The Omote Ginza route', body: "The heart of the traverse, along the Omote Ginza route. The trail follows the watershed line, between scree and slopes of close cropped grass, with the Northern Alps on either side.", tags: ['High mountain', 'Mountain hut'] },
      { n: 8, title: 'Ascent of a summit above 3,000 metres', body: "The highest stage of the trip, with the ascent of a summit above 3,000 metres. An early start, a lightened pack, and a view that reaches as far as Fuji in clear weather.", tags: ['Summit', '3,000 m', 'Mountain hut'] },
      { n: 9, title: 'Descent to the valley and onsen', body: "After five days walking above 2,500 metres, you return to the valley. The descent passes through alpine vegetation, its lakes and its rivers. A gentle return, and a long evening in the baths of the Yarimikan ryokan. 150 m of ascent, 1,550 m of descent, 6 hrs 30 to 7 hrs of walking.", tags: ['Descent', 'Onsen', 'Ryokan'] },
      { n: 10, title: 'Kamikōchi, then Kyoto', body: "Coach transfer to the village of Kamikōchi, the capital of the Japanese Alps, and a discovery of the valley. On the road to Kyoto in the afternoon, reunited with your luggage and check in at the hotel.", tags: ['Kamikōchi', 'Coach', 'Hotel'] },
      { n: 11, title: 'Kyoto', body: "A day in Kyoto. Temples, gardens and lanes of the old capital, on foot and at your own pace.", tags: ['City', 'Temples'] },
      { n: 12, title: 'Return flight', body: "Transfer to the airport and return flight to France.", tags: ['Flight'] },
    ],
  },
};
