// Itinerarios: tarjetas, pagina de indice, fichas Kunisaki y Alpes japoneses.
// Version espanola, traducida del frances.
export default {
  circuitsLong: {
    'CL-01': { title: 'Del Neón al Silencio', duree: '14 días / 13 noches', ribbon: 'Cultural' },
    'CL-02': { title: 'Mil Escalones hacia el Norte', duree: '14 días / 13 noches', ribbon: 'Espiritual' },
    'CL-03': { title: 'De los Templos a los Corales', duree: '14 días / 13 noches', ribbon: 'Bienestar' },
    'CL-04': { title: 'El Primer Aliento', duree: '7 días / 6 noches', ribbon: 'Cultural' },
    'CL-05': { title: 'El Corazón del Viejo Japón', duree: '7 días / 6 noches', ribbon: 'Artes Marciales' },
    'CL-06': { title: 'La Travesía sin Prisa', duree: '21 días / 20 noches', ribbon: 'Gastronomía' },
    'CL-07': { title: 'De las Torres a los Tejados de Paja', duree: '21 días / 20 noches', ribbon: 'Anime & Manga' },
    'CL-08': { title: 'Hasta los Cedros Milenarios', duree: '22 días / 21 noches', ribbon: 'Miyazaki' },
    'CL-09': { title: 'Tokio, Kioto y travesía meridional de los Alpes japoneses', duree: '12 días / 11 noches', ribbon: 'Senderismo', privateNote: '4 a 8 en grupo reducido' },
  },

  circuitsCourts: {
    'CT-01': { title: 'El Tokio de los Neones', zone: 'Shinjuku, Harajuku, Shibuya', intensite: 'Intensa' },
    'CT-02': { title: 'El Tokio de Edo', zone: 'Asakusa, Ueno, Akihabara', intensite: 'Moderada' },
    'CT-03': { title: 'El Tokio de las Alturas y la Bahía', zone: 'Asakusa, Skytree, Odaiba', intensite: 'Moderada' },
    'CT-04': { title: 'El Tokio Letrado', zone: 'Ueno, Akihabara, Kanda, Jimbocho', intensite: 'Moderada' },
    'CT-05': { title: 'El Tokio de los Panoramas', zone: 'Shinjuku, Roppongi, Daimon', intensite: 'Moderada' },
    'CT-06': { title: 'El Tokio de la Imaginación', zone: 'Ghibli, Kichijoji, Koenji, Nakano', intensite: 'Suave' },
    'CT-07': { title: 'Yokohama, la Puerta del Mar Abierto', zone: 'Kanagawa', intensite: 'Suave' },
    'CT-08': { title: 'Enoshima y Kamakura', zone: 'Kanagawa', intensite: 'Intensa' },
    'CT-09': { title: 'Takaosan, la Montaña de los Tengu', zone: 'Tokio oeste', intensite: 'Exigente' },
    'CT-10': { title: 'Nikko, el Santuario entre los Cedros', zone: 'Tochigi', intensite: 'Moderada a exigente' },
    'CT-11': { title: 'Kioto Centro', zone: 'Palacio imperial, Nishiki, Gion', intensite: 'Suave' },
    'CT-12': { title: 'Kioto Este, el Camino del Filósofo', zone: 'Higashiyama norte', intensite: 'Intensa' },
    'CT-13': { title: 'Kioto Norte', zone: 'Arashiyama, Hozugawa, Kinkakuji', intensite: 'Moderada' },
    'CT-14': { title: 'Kioto, los Diez Mil Torii', zone: 'Fushimi Inari, Higashiyama sur', intensite: 'Exigente' },
    'CT-15': { title: 'Osaka, la Ciudad que Come', zone: 'Umeda, castillo de Osaka', intensite: 'Suave' },
    'CT-16': { title: 'Osaka Popular', zone: 'Shinsekai, Shitennoji, Namba, Dotonbori', intensite: 'Moderada' },
    'EX-01': { title: 'El Verano de las Ryukyu', zone: 'Extensión', intensite: '5 días / 4 noches' },
  },

  index: {
    eyebrow: 'NUESTROS ITINERARIOS LARGOS',
    titre: 'Nueve circuitos, de siete a veintidós días.',
    kicker: '· cada uno retejido en torno a usted.',
    droite: "Sin fechas impuestas en viaje privado: usted parte cuando quiere, durante el tiempo que quiere. De uno a ocho viajeros en privado, de cuatro a ocho en grupo reducido.",
    courtsEyebrow: 'ITINERARIOS CORTOS',
    courtsTitre: 'Dieciséis módulos de un día.',
    courtsKicker: '· sin alojamiento ni transporte de larga distancia.',
    courtsDroite: "Extensiones, escalas o piezas para componer un circuito a medida. Más una extensión de cinco días.",
    thRef: 'Ref.',
    thNom: 'Nombre',
    thZone: 'Zona',
    thIntensite: 'Intensidad',
    bouton: 'Reservar una llamada de treinta minutos',
    note: "Usted nos cuenta lo que le apetece. Nosotros le decimos si es la estación adecuada.",
  },

  carrousels: {
    'CL-09': ['Tokio y el Fuji, a la salida', 'La cresta, más allá de los 2.500 metros', 'La subida por el bosque hacia Enzanso', 'Kioto, a la llegada'],
    KUNISAKI: ['El sendero de Futagoji', 'Teñido aizome con Tanaka-san', 'Un onsen de barrio en Beppu', 'El mercado de pescado de Saiki'],
  },

  kunisaki: {
    fil: 'Kunisaki, siete días',
    eyebrow: 'UNA EXPERIENCIA · KYUSHU',
    titre: 'Siete días por el sendero de Kunisaki.',
    ledeAvant: "La península olvidada de Kyushu, sus templos Tendai escondidos en el bosque, un día entero de teñido ",
    ledeItalique: 'aizome',
    ledeApres: " con Tanaka-san, y un onsen secreto en Beppu, ese donde se pagan 200 yenes a una señora.",
    detailTitre: 'Siete mañanas, siete cenas.',
    prix: '3.980 €',
    prixSub: 'por viajero, en habitación doble · vuelos no incluidos',
    recap: "Oita · sendero de Futagoji · taller de aizome en casa de Tanaka-san · onsen de barrio en Beppu · mercado de Saiki · monte Tsurumi · Fukuoka",
    note: "Los vuelos internacionales no están incluidos, le ayudamos a reservarlos en el mejor horario. La temporada va de abril a junio, la península es más bella antes de las lluvias. Un viaje lento, por una península que los circuitos clásicos ignoran. Usted duerme en minshuku y en ryokan, come lo que se ha pescado por la mañana y camina por senderos de templos que pocos viajeros recorren.",
    plus: [
      "Una península que los circuitos clásicos ignoran, sin ningún otro grupo en los senderos",
      "Seis noches en minshuku y en ryokan, todas las cenas incluidas",
      "Un día entero de teñido aizome con Tanaka-san, usted se lleva su propia tela",
      "El mercado de pescado de Saiki a primera hora, con el almuerzo elegido y preparado allí mismo",
      "Un onsen de barrio en Beppu, ese donde se pagan 200 yenes a la señora de la entrada",
      "De uno a ocho viajeros, en la fecha que usted elija, sin fechas impuestas",
    ],
    facts: [
      { lbl: 'Salidas', val: 'En la fecha que usted elija' },
      { lbl: 'Duración', val: '7 días / 6 noches' },
      { lbl: 'Nivel', val: 'Caminata suave' },
      { lbl: 'Viajeros', val: '1 a 8 personas' },
      { lbl: 'Pensión', val: 'Pensión completa, salvo las tardes libres' },
      { lbl: 'Alojamiento', val: 'Minshuku y ryokan' },
    ],
    jours: [
      { n: 1, title: 'Llegada a Oita, cena en casa de Mariko-san', body: "Vuelo directo París → Tokio, después shinkansen hasta Kokura y línea local. Le esperamos en la estación con un termo. Cena familiar en el minshuku, pescado a la brasa, arroz local y un largo baño.", tags: ['Tren local', 'Minshuku', 'Cocina casera'] },
      { n: 2, title: 'Primer sendero: Futagoji', body: "Treinta kilómetros a pie a través de los templos Tendai escondidos en el bosque. Se camina despacio. Pausa del mediodía en casa de un monje que prepara su propio nattō.", tags: ['Senderismo', 'Templo', 'Almuerzo en el templo'] },
      { n: 3, title: 'Taller de teñido aizome con Tanaka-san', body: "Un día entero aprendiendo el teñido con índigo. Tanaka-san tiene 78 años, no tiene internet y le dejará marcharse con su propia tela, secada al viento.", tags: ['Artesanía', 'Un día entero'] },
      { n: 4, title: 'Onsen secreto en Beppu, versión local', body: "No son los onsen de la guía. Un pequeño baño de barrio donde se pagan 200 yenes a una señora que le entrega una toalla. Siesta por la tarde, cena de izakaya por la noche.", tags: ['Onsen', 'Izakaya'] },
      { n: 5, title: 'El mercado de pescado de Saiki', body: "En pie a las 5 h. Allí uno se cruza con los pescadores que regresan, elige el almuerzo sobre la marcha y un cocinero nos lo prepara en sashimi a las 10 de la mañana. Tarde libre.", tags: ['Mercado', 'Comida'] },
      { n: 6, title: 'Baño de bosque en el monte Tsurumi', body: "Caminata suave, seis horas, pausa de meditación en un claro. Cena en el ryokan, kaiseki de temporada, nueve pequeños platos preparados por la dueña.", tags: ['Caminata suave', 'Kaiseki'] },
      { n: 7, title: 'Regreso a Fukuoka, último kissaten', body: "Se vuelve tranquilamente a Fukuoka. Un último café en un kissaten de antes de la guerra, regentado por el mismo señor desde hace 47 años, y se acabó.", tags: ['Kissaten', 'Regreso'] },
    ],
  },

  alpes: {
    fil: 'Alpes japoneses, doce días',
    eyebrow: 'ITINERARIO LARGO · CL-09 · SENDERISMO',
    titre: 'Tokio, Kioto y travesía meridional de los Alpes japoneses',
    lede: "Una travesía meridional de los Alpes del norte, en cinco etapas por la vía Omote Ginza, con la ascensión a una cumbre de más de 3.000 metros. Cinco días de alta montaña por encima de los 2.500 metros, enmarcados por Tokio a la salida y Kioto a la llegada.",
    detailTitre: 'Doce días, seis de ellos en montaña.',
    detailKicker: '· el trek ocupa los días 5 a 10.',
    prix: '3.990 €',
    prixSub: 'por persona, en habitación twin · vuelos y traslado no incluidos',
    recap: "Tokio, 3 días · Matsumoto · Nakabusa onsen · refugios Enzanso, Tsubakuro, Jōnen · vía Omote Ginza · cumbre de 3.000 m · ryokan Yarimikan · Kamikōchi · Kioto, 2 días",
    note: "Los vuelos internacionales no están incluidos, le ayudamos a reservarlos en el mejor horario. El circuito solo sale en agosto y en septiembre, ya que los senderos de altitud solo son practicables en verano. El trek transcurre durante cinco días por encima de los 2.500 metros, con porteo ligero en autonomía: su equipaje viaja de Tokio a Kioto mientras usted camina. Se necesitan una buena condición física y experiencia en media montaña.",
    plus: [
      "Cinco días de alta montaña por encima de los 2.500 metros, por la vía Omote Ginza",
      "La ascensión a una cumbre de más de 3.000 metros, con mochila aligerada y salida al amanecer",
      "Grupo reducido de 4 a 8 personas, acompañado por un guía de alta montaña hispanohablante",
      "Su equipaje viaja de Tokio a Kioto mientras usted camina, solo lleva lo imprescindible",
      "Una noche en el ryokan Yarimikan y sus onsen, tras el descenso hacia el valle",
      "Tokio a la salida y Kioto a la llegada, con un guía en cada una de las dos ciudades",
    ],
    facts: [
      { lbl: 'Próxima salida', val: '27 sept. 2026' },
      { lbl: 'Duración', val: '12 días / 11 noches' },
      { lbl: 'Nivel', val: 'Avanzado · 5 a 7 h de caminata' },
      { lbl: 'Grupo', val: '4 a 8 personas' },
      { lbl: 'Pensión', val: 'Pensión completa, días 3 a 11' },
      { lbl: 'Alojamiento', val: 'Hoteles 3★ y refugios' },
    ],
    departs: [
      { du: '27 de septiembre de 2026', au: '8 de octubre de 2026', prix: '3.990,00 €' },
      { du: '1 de agosto de 2027', au: '12 de agosto de 2027', prix: '4.250,00 €' },
      { du: '26 de septiembre de 2027', au: '7 de octubre de 2027', prix: '4.250,00 €' },
    ],
    jours: [
      { n: 1, title: 'Vuelo a Tokio', body: "Salida desde Francia. Vuelo a Tokio, comidas y noche a bordo según el horario de su compañía.", tags: ['Vuelo'] },
      { n: 2, title: 'Llegada a Tokio', body: "Recepción en el aeropuerto, traslado e instalación en el hotel. El resto del día queda libre, el tiempo de dejar que el desfase horario se asiente.", tags: ['Traslado', 'Hotel'] },
      { n: 3, title: 'Tokio con su guía', body: "Jornada en la capital con su guía tokiota, de los grandes santuarios a los barrios que nunca duermen. Desayuno, almuerzo y cena incluidos.", tags: ['Ciudad', 'Guía hispanohablante'] },
      { n: 4, title: 'Tokio, Matsumoto y Nakabusa onsen', body: "Usted deja su equipaje en el hotel y se queda solo con sus cosas de trek para los días 5 a 10: las recuperará en Kioto. Tren hasta Matsumoto (2 h 30), visita del castillo y después carretera hacia Nakabusa onsen (1 h), punto de partida del trek. Noche en el refugio Ariake.", tags: ['Tren', 'Castillo de Matsumoto', 'Refugio'] },
      { n: 5, title: 'Subida al refugio Enzanso y monte Tsubakuro', body: "La itinerancia comienza con una subida regular por el bosque hasta el refugio Enzanso. Los primeros panoramas se abren sobre las cadenas alpinas. Tras un alto en el refugio, usted continúa hasta el monte Tsubakuro y sus rocas graníticas de formas extrañas.", tags: ['Subida por el bosque', 'Panorama', 'Refugio'] },
      { n: 6, title: 'Por la cresta, hacia el monte Jōnen', body: "Jornada de cresta a más de 2.500 metros. Una colonia de macacos vive al pie del monte Jōnen: con un poco de paciencia, se cruzará con ellos. Para quienes quieran prolongar, una variante añade una cumbre a la etapa.", tags: ['Cresta', 'Fauna', 'Refugio'] },
      { n: 7, title: 'La vía Omote Ginza', body: "El corazón de la travesía, por la vía Omote Ginza. El sendero sigue la línea divisoria de aguas, entre pedreras y laderas de hierba rasa, con los Alpes del norte a uno y otro lado.", tags: ['Alta montaña', 'Refugio'] },
      { n: 8, title: 'Ascensión a una cumbre de más de 3.000 metros', body: "La etapa más alta de la estancia, con la ascensión a una cumbre de más de 3.000 metros. Salida temprano, mochila aligerada y una vista que alcanza hasta el Fuji si el tiempo es claro.", tags: ['Cumbre', '3.000 m', 'Refugio'] },
      { n: 9, title: 'Descenso hacia el valle y onsen', body: "Después de cinco días caminando por encima de los 2.500 metros, usted vuelve a encontrar el valle. El descenso atraviesa una vegetación alpina, sus lagos y sus ríos. Regreso suave y larga velada en los baños del ryokan Yarimikan. D+ 150 m, D- 1.550 m, de 6 h 30 a 7 h de caminata.", tags: ['Descenso', 'Onsen', 'Ryokan'] },
      { n: 10, title: 'Kamikōchi, después Kioto', body: "Traslado en autocar hasta el pueblo de Kamikōchi, la capital de los Alpes japoneses, y descubrimiento del valle. Carretera hacia Kioto por la tarde, reencuentro con su equipaje e instalación en el hotel.", tags: ['Kamikōchi', 'Autocar', 'Hotel'] },
      { n: 11, title: 'Kioto', body: "Jornada en Kioto. Templos, jardines y callejuelas de la antigua capital, a pie y a su ritmo.", tags: ['Ciudad', 'Templos'] },
      { n: 12, title: 'Vuelo de regreso', body: "Traslado al aeropuerto y vuelo de regreso a Francia.", tags: ['Vuelo'] },
    ],
  },
};
