// Itineraires : cartes, page d'index, fiches Kunisaki et Alpes japonaises.
// Version francaise, reference des traductions.
export default {
  circuitsLong: {
    'CL-01': { title: 'Du Néon au Silence', duree: '14 j / 13 n', ribbon: 'Culturel' },
    'CL-02': { title: 'Mille Marches vers le Nord', duree: '14 j / 13 n', ribbon: 'Spirituel' },
    'CL-03': { title: 'Des Temples aux Coraux', duree: '14 j / 13 n', ribbon: 'Bien Être' },
    'CL-04': { title: 'Le Premier Souffle', duree: '7 j / 6 n', ribbon: 'Culturel' },
    'CL-05': { title: 'Au Cœur du Vieux Japon', duree: '7 j / 6 n', ribbon: 'Arts Martiaux' },
    'CL-06': { title: 'La Traversée sans Hâte', duree: '21 j / 20 n', ribbon: 'Gastronomie' },
    'CL-07': { title: 'Des Tours aux Toits de Chaume', duree: '21 j / 20 n', ribbon: 'Anime & Manga' },
    'CL-08': { title: "Jusqu'aux Cèdres Millénaires", duree: '22 j / 21 n', ribbon: 'Miyazaki' },
    'CL-09': { title: 'Tokyo, Kyoto et traversée méridionale des Alpes japonaises', duree: '12 j / 11 n', ribbon: 'Randonnée', privateNote: '4 à 8 en petit groupe' },
  },

  circuitsCourts: {
    'CT-01': { title: 'Le Tokyo des Néons', zone: 'Shinjuku, Harajuku, Shibuya', intensite: 'Soutenue' },
    'CT-02': { title: "Le Tokyo d'Edo", zone: 'Asakusa, Ueno, Akihabara', intensite: 'Modérée' },
    'CT-03': { title: 'Le Tokyo des Hauteurs et de la Baie', zone: 'Asakusa, Skytree, Odaiba', intensite: 'Modérée' },
    'CT-04': { title: 'Le Tokyo Lettré', zone: 'Ueno, Akihabara, Kanda, Jimbocho', intensite: 'Modérée' },
    'CT-05': { title: 'Le Tokyo des Panoramas', zone: 'Shinjuku, Roppongi, Daimon', intensite: 'Modérée' },
    'CT-06': { title: "Le Tokyo de l'Imaginaire", zone: 'Ghibli, Kichijoji, Koenji, Nakano', intensite: 'Douce' },
    'CT-07': { title: 'Yokohama, la Porte du Large', zone: 'Kanagawa', intensite: 'Douce' },
    'CT-08': { title: 'Enoshima et Kamakura', zone: 'Kanagawa', intensite: 'Soutenue' },
    'CT-09': { title: 'Takaosan, la Montagne des Tengu', zone: 'Tokyo ouest', intensite: 'Sportive' },
    'CT-10': { title: 'Nikko, le Sanctuaire dans les Cèdres', zone: 'Tochigi', intensite: 'Modérée à sportive' },
    'CT-11': { title: 'Kyoto Centre', zone: 'Palais impérial, Nishiki, Gion', intensite: 'Douce' },
    'CT-12': { title: 'Kyoto Est, le Chemin des Philosophes', zone: 'Higashiyama nord', intensite: 'Soutenue' },
    'CT-13': { title: 'Kyoto Nord', zone: 'Arashiyama, Hozugawa, Kinkakuji', intensite: 'Modérée' },
    'CT-14': { title: 'Kyoto, les Dix Mille Torii', zone: 'Fushimi Inari, Higashiyama sud', intensite: 'Sportive' },
    'CT-15': { title: 'Osaka, la Ville qui Mange', zone: "Umeda, château d'Osaka", intensite: 'Douce' },
    'CT-16': { title: 'Osaka Populaire', zone: 'Shinsekai, Shitennoji, Namba, Dotonbori', intensite: 'Modérée' },
    'EX-01': { title: "L'Été des Ryukyu", zone: 'Extension', intensite: '5 j / 4 n' },
  },

  index: {
    eyebrow: 'NOS ITINÉRAIRES LONGS',
    titre: 'Neuf circuits, de sept à vingt-deux jours.',
    kicker: '· chacun retissé autour de vous.',
    droite: "Pas de date imposée en voyage privé : vous partez quand vous voulez, pour la durée que vous voulez. De un à huit voyageurs en privé, de quatre à huit en petit groupe.",
    courtsEyebrow: 'ITINÉRAIRES COURTS',
    courtsTitre: "Seize modules d'une journée.",
    courtsKicker: '· sans hébergement ni transport longue distance.',
    courtsDroite: "Des extensions, des escales, ou des briques pour composer un circuit sur mesure. Plus une extension de cinq jours.",
    thRef: 'Réf',
    thNom: 'Nom',
    thZone: 'Zone',
    thIntensite: 'Intensité',
    bouton: 'Réserver un appel de trente minutes',
    note: "Vous nous racontez ce qui vous tente. On vous dit si c'est la bonne saison.",
  },

  carrousels: {
    'CL-09': ['Tokyo et le Fuji, au départ', 'La crête, au-delà de 2 500 mètres', 'La montée en forêt vers Enzanso', "Kyoto, à l'arrivée"],
    KUNISAKI: ['Le sentier de Futagoji', 'Teinture aizome avec Tanaka-san', 'Un onsen de quartier à Beppu', 'Le marché de poissons de Saiki'],
  },

  kunisaki: {
    fil: 'Kunisaki, sept jours',
    eyebrow: 'UNE EXPÉRIENCE · KYUSHU',
    titre: 'Sept jours sur le sentier de Kunisaki.',
    ledeAvant: "La péninsule oubliée du Kyushu, ses temples Tendai cachés dans la forêt, une journée entière de teinture ",
    ledeItalique: 'aizome',
    ledeApres: " avec Tanaka-san, et un onsen secret à Beppu, celui où on paye 200 yens à une dame.",
    detailTitre: 'Sept matinées, sept dîners.',
    prix: '3 980 €',
    prixSub: 'par voyageur, base chambre double · vols non inclus',
    recap: "Oita · sentier de Futagoji · atelier aizome chez Tanaka-san · onsen de quartier à Beppu · marché de Saiki · mont Tsurumi · Fukuoka",
    note: "Les vols internationaux ne sont pas inclus, nous vous aidons à les réserver au meilleur horaire. La saison va d'avril à juin, la péninsule est plus belle avant les pluies. Un voyage lent, dans une péninsule que les circuits classiques ignorent. Vous dormez en minshuku et en ryokan, vous mangez ce qui a été pêché le matin, et vous marchez sur des sentiers de temples que peu de voyageurs empruntent.",
    plus: [
      "Une péninsule que les circuits classiques ignorent, sans autre groupe sur les sentiers",
      "Six nuits en minshuku et en ryokan, tous les dîners inclus",
      "Une journée entière de teinture aizome avec Tanaka-san, vous repartez avec votre tissu",
      "Le marché de poissons de Saiki au petit matin, déjeuner choisi et préparé sur place",
      "Un onsen de quartier à Beppu, celui où on paye 200 yens à la dame de l'entrée",
      "De un à huit voyageurs, à la date de votre choix, sans date imposée",
    ],
    facts: [
      { lbl: 'Départs', val: 'À la date de votre choix' },
      { lbl: 'Durée', val: '7 jours / 6 nuits' },
      { lbl: 'Niveau', val: 'Marche douce' },
      { lbl: 'Voyageurs', val: '1 à 8 personnes' },
      { lbl: 'Pension', val: 'Pension complète, sauf après-midi libres' },
      { lbl: 'Hébergement', val: 'Minshuku et ryokan' },
    ],
    jours: [
      { n: 1, title: 'Arrivée à Oita, dîner chez Mariko-san', body: "Vol direct Paris → Tokyo, puis Shinkansen jusqu'à Kokura, puis ligne locale. On vous attend à la gare avec un thermos. Dîner familial au minshuku, du poisson grillé, du riz local, et un long bain.", tags: ['Train local', 'Minshuku', 'Cuisine maison'] },
      { n: 2, title: 'Premier sentier : Futagoji', body: "Trente kilomètres à pied à travers les temples Tendai cachés dans la forêt. On marche lentement. Pause de midi chez un moine qui prépare son propre nattō.", tags: ['Randonnée', 'Temple', 'Déjeuner au temple'] },
      { n: 3, title: 'Atelier de teinture aizome avec Tanaka-san', body: "Journée entière à apprendre la teinture à l'indigo. Tanaka-san a 78 ans, n'a pas internet, et vous laissera repartir avec votre propre tissu, séché au vent.", tags: ['Artisanat', 'Une journée entière'] },
      { n: 4, title: 'Onsen secret à Beppu, version locale', body: "Pas les onsens du guide. Un petit bain de quartier où on paye 200 yens à une dame qui vous donne une serviette. Sieste l'après-midi, dîner d'izakaya le soir.", tags: ['Onsen', 'Izakaya'] },
      { n: 5, title: 'Le marché de poissons de Saiki', body: "Lever 5 h. On y croise les pêcheurs qui rentrent, on choisit le déjeuner sur place, et un cuisinier nous le prépare en sashimi à 10 h du matin. Après-midi libre.", tags: ['Marché', 'Repas'] },
      { n: 6, title: 'Bain de forêt au mont Tsurumi', body: "Marche douce, six heures, pause méditation dans une clairière. Repas du soir au ryokan, kaiseki saisonnier, neuf petits plats préparés par la patronne.", tags: ['Marche douce', 'Kaiseki'] },
      { n: 7, title: 'Retour à Fukuoka, dernier kissaten', body: "On rentre tranquillement à Fukuoka. Un dernier café dans un kissaten d'avant-guerre tenu par le même monsieur depuis 47 ans, et c'est terminé.", tags: ['Kissaten', 'Retour'] },
    ],
  },

  alpes: {
    fil: 'Alpes japonaises, douze jours',
    eyebrow: 'ITINÉRAIRE LONG · CL-09 · RANDONNÉE',
    titre: 'Tokyo, Kyoto et traversée méridionale des Alpes japonaises',
    lede: "Une traversée méridionale des Alpes du nord, en cinq étapes sur la voie Omote Ginza, avec l'ascension d'un sommet à plus de 3 000 mètres. Cinq jours de haute montagne au-delà de 2 500 mètres, encadrés par Tokyo au départ et Kyoto à l'arrivée.",
    detailTitre: 'Douze jours, dont six en montagne.',
    detailKicker: '· le trek occupe les jours 5 à 10.',
    prix: '3 990 €',
    prixSub: 'par personne, base chambre twin · vols et transfert non inclus',
    recap: "Tokyo, 3 jours · Matsumoto · Nakabusa onsen · refuges Enzanso, Tsubakuro, Jōnen · voie Omote Ginza · sommet à 3 000 m · ryokan Yarimikan · Kamikōchi · Kyoto, 2 jours",
    note: "Les vols internationaux ne sont pas inclus, nous vous aidons à les réserver au meilleur horaire. Le circuit ne part qu'en août et en septembre, les sentiers d'altitude n'étant praticables qu'en été. Le trek se déroule cinq jours durant au-delà de 2 500 mètres, en autonomie de portage léger : vos bagages voyagent de Tokyo à Kyoto pendant que vous marchez. Une bonne condition physique et une expérience de la moyenne montagne sont nécessaires.",
    plus: [
      "Cinq jours de haute montagne au-delà de 2 500 mètres, sur la voie Omote Ginza",
      "L'ascension d'un sommet à plus de 3 000 mètres, sac allégé, départ au petit jour",
      "Petit groupe de 4 à 8 personnes, encadré par un guide francophone de haute montagne",
      "Vos bagages voyagent de Tokyo à Kyoto pendant que vous marchez, vous ne portez que le nécessaire",
      "Une nuit au ryokan Yarimikan et ses onsen, après la descente vers la vallée",
      "Tokyo au départ et Kyoto à l'arrivée, avec un guide sur chacune des deux villes",
    ],
    facts: [
      { lbl: 'Prochain départ', val: '27 sept. 2026' },
      { lbl: 'Durée', val: '12 jours / 11 nuits' },
      { lbl: 'Niveau', val: 'Confirmé · 5 à 7 h de marche' },
      { lbl: 'Groupe', val: '4 à 8 personnes' },
      { lbl: 'Pension', val: 'Pension complète, jours 3 à 11' },
      { lbl: 'Hébergement', val: 'Hôtels 3★ et refuges' },
    ],
    departs: [
      { du: '27 septembre 2026', au: '8 octobre 2026', prix: '3 990,00 €' },
      { du: '1 août 2027', au: '12 août 2027', prix: '4 250,00 €' },
      { du: '26 septembre 2027', au: '7 octobre 2027', prix: '4 250,00 €' },
    ],
    jours: [
      { n: 1, title: 'Vol pour Tokyo', body: "Départ de France. Vol pour Tokyo, repas et nuit à bord selon l'horaire de votre compagnie.", tags: ['Vol'] },
      { n: 2, title: 'Arrivée à Tokyo', body: "Accueil à l'aéroport, transfert et installation à l'hôtel. Le reste de la journée est libre, le temps de laisser le décalage se poser.", tags: ['Transfert', 'Hôtel'] },
      { n: 3, title: 'Tokyo avec votre guide', body: "Journée dans la capitale avec votre guide tokyoïte, des grands sanctuaires aux quartiers qui ne dorment jamais. Petit-déjeuner, déjeuner et dîner inclus.", tags: ['Ville', 'Guide francophone'] },
      { n: 4, title: 'Tokyo, Matsumoto et Nakabusa onsen', body: "Vous confiez vos bagages à l'hôtel et ne gardez que vos affaires de trek pour les jours 5 à 10 : vous les retrouverez à Kyoto. Train jusqu'à Matsumoto (2 h 30), visite du château, puis route vers Nakabusa onsen (1 h), point de départ du trek. Nuit au refuge Ariake.", tags: ['Train', 'Château de Matsumoto', 'Refuge'] },
      { n: 5, title: 'Montée au refuge Enzanso et mont Tsubakuro', body: "L'itinérance débute par une montée régulière en forêt jusqu'au refuge Enzanso. Les premiers panoramas ouvrent sur les chaînes alpines. Après une halte au refuge, vous poursuivez jusqu'au mont Tsubakuro et ses roches granitiques aux formes étranges.", tags: ['Montée en forêt', 'Panorama', 'Refuge'] },
      { n: 6, title: 'Sur la crête, vers le mont Jōnen', body: "Journée de crête à plus de 2 500 mètres. Une colonie de macaques est installée au pied du mont Jōnen : avec un peu de patience, vous les croiserez. Pour celles et ceux qui veulent prolonger, une variante ajoute un sommet à l'étape.", tags: ['Crête', 'Faune', 'Refuge'] },
      { n: 7, title: 'La voie Omote Ginza', body: "Le cœur de la traversée, sur la voie Omote Ginza. Le sentier suit la ligne de partage des eaux, entre pierriers et pentes d'herbe rase, avec les Alpes du nord de part et d'autre.", tags: ['Haute montagne', 'Refuge'] },
      { n: 8, title: "Ascension d'un sommet à plus de 3 000 mètres", body: "L'étape la plus haute du séjour, avec l'ascension d'un sommet à plus de 3 000 mètres. Départ tôt, sac allégé, et une vue qui porte jusqu'au Fuji par temps clair.", tags: ['Sommet', '3 000 m', 'Refuge'] },
      { n: 9, title: 'Descente vers la vallée et onsen', body: "Après cinq jours passés à randonner au-delà de 2 500 mètres, vous retrouvez la vallée. La descente traverse une végétation alpine, ses lacs et ses rivières. Retour en douceur, et longue soirée aux bains du ryokan Yarimikan. D+ 150 m, D- 1 550 m, 6 h 30 à 7 h de marche.", tags: ['Descente', 'Onsen', 'Ryokan'] },
      { n: 10, title: 'Kamikōchi, puis Kyoto', body: "Transfert en car jusqu'au village de Kamikōchi, la capitale des Alpes japonaises, et découverte de la vallée. Route vers Kyoto dans l'après-midi, retrouvailles avec vos bagages et installation à l'hôtel.", tags: ['Kamikōchi', 'Car', 'Hôtel'] },
      { n: 11, title: 'Kyoto', body: "Journée à Kyoto. Temples, jardins et ruelles de l'ancienne capitale, à pied et à votre rythme.", tags: ['Ville', 'Temples'] },
      { n: 12, title: 'Vol de retour', body: "Transfert vers l'aéroport et vol de retour vers la France.", tags: ['Vol'] },
    ],
  },
};
