// Le Japon (hub, histoire, gastronomie) et guide pratique.
// Version francaise, reference des traductions.
export default {
  hub: {
    eyebrow: 'LE JAPON',
    titre: 'Le pays avant le voyage.',
    lede: "Deux entrées pour comprendre où vous allez : les ères qui ont façonné le pays, et la cuisine qui en raconte la géographie, préfecture par préfecture.",
    sousPage: 'SOUS-PAGE',
    histoireTitre: 'Histoire',
    histoireTexte: "Le Japon ne se raconte pas comme une ligne droite. C'est une succession d'ères, certaines fondatrices, d'autres simplement calmes. On ne raconte que celles qui ont vraiment façonné le pays que vous allez visiter.",
    gastroTitre: 'Gastronomie',
    gastroTexte: "Le Japon ne se mange pas de la même façon d'un bout à l'autre de l'archipel. Chaque préfecture a ses produits, ses techniques, ses plats qu'on ne trouve qu'ici.",
    photo: 'Photo',
  },

  histoire: {
    eyebrow: 'LE JAPON · HISTOIRE',
    titre: 'Trois ères, et le pays que vous allez visiter.',
    lede: "Le Japon ne se raconte pas comme une ligne droite. C'est une succession d'ères, certaines fondatrices, d'autres simplement calmes. On ne raconte que celles qui ont vraiment façonné le pays que vous allez visiter.",
    aParaitre: 'À PARAÎTRE',
    eres: [
      { nom: 'Heian', annees: '794 · 1185', sur: 'La cour de Kyoto',
        txt: "La capitale se déplace à Kyoto. Pendant quatre siècles, une aristocratie raffinée invente une grande partie de l'esthétique japonaise : la littérature de cour, le culte de la saison, un sens du beau qui n'a jamais vraiment quitté le pays." },
      { nom: 'Edo', annees: '1603 · 1868', sur: 'La paix des Tokugawa',
        txt: "Deux cent cinquante ans de paix imposée par les shoguns Tokugawa, un pays fermé sur lui-même, et l'essor d'une culture urbaine et marchande : l'estampe, le kabuki, les grandes routes comme le Nakasendo que l'on parcourt encore aujourd'hui." },
      { nom: 'Meiji', annees: '1868 · 1912', sur: "L'ouverture",
        txt: "Le pays s'ouvre par la force au commerce occidental, puis se modernise à une vitesse inédite : industrie, armée, institutions occidentales, tout en gardant l'empereur comme figure centrale." },
    ],
    reserve: [
      "Les origines, jusqu'au VIIe siècle",
      "Nara et l'arrivée du bouddhisme",
      'Kamakura, les premiers shoguns',
      "Muromachi, l'âge des guerres",
      'Guerre et reconstruction',
      'Le Japon contemporain',
    ],
  },

  gastronomie: {
    eyebrow: 'LE JAPON · GASTRONOMIE',
    titre: "La géographie racontée dans l'assiette.",
    lede: "Le Japon ne se mange pas de la même façon d'un bout à l'autre de l'archipel. Chaque préfecture a ses produits, ses techniques, ses plats qu'on ne trouve qu'ici. Cette page se construit préfecture par préfecture, au fil de nos voyages et de nos rencontres avec les producteurs et les cuisiniers.",
    photoDe: 'Photo, cuisine de',
    prefectures: [
      { nom: 'Tokyo', num: 'Préfecture 13',
        txt: "La capitale a inventé le sushi tel qu'on le connaît aujourd'hui : l'Edomae, né sur les quais de la baie d'Edo, pensé pour se manger vite et debout. On y trouve aussi le tempura, la friture légère venue du XVIe siècle, l'anguille grillée (unagi) et le soba, la nouille de sarrasin des artisans d'Edo. Tokyo est une ville de spécialistes : un restaurant, un plat, toute une vie à le perfectionner." },
      { nom: 'Kyoto', num: 'Préfecture 26',
        txt: "Ancienne capitale impériale, Kyoto a donné naissance au kaiseki, le repas en plusieurs services qui suit les saisons à la lettre. La ville vit aussi de son tofu, réputé pour la pureté de son eau, de sa cuisine végétarienne des temples bouddhistes (shojin ryori), et de son obanzai, la cuisine familiale kyotoïte, discrète et jamais gaspillée. C'est enfin la capitale du thé et des wagashi, les pâtisseries pensées pour l'accompagner." },
      { nom: 'Osaka', num: 'Préfecture 27',
        txt: "Osaka se surnomme elle-même « la cuisine du pays » (tenka no daidokoro). Ville marchande, elle a fait de la rue sa table : takoyaki (boulettes de poulpe), okonomiyaki (galette garnie), kushikatsu (brochettes panées). Une cuisine généreuse, populaire, pensée pour se partager entre amis, à l'opposé de la retenue de Kyoto à quelques dizaines de kilomètres." },
    ],
    suite: "Les quarante-quatre autres préfectures s'ajouteront au fil des voyages. Chaque fiche part d'un producteur, d'un cuisinier, ou d'un plat qu'on ne trouve nulle part ailleurs.",
    compteur: '3 / 47 publiées',
  },

  guide: {
    eyebrow: 'GUIDE PRATIQUE',
    titre: 'La boîte à outils du voyage.',
    lede: "Les transports, la carte Suica, les usages de table, et de quoi déchiffrer une enseigne. Ce qu'il faut savoir avant de partir, et ce qu'on vous prépare sur place.",
    blocs: [
      { t: 'Le métro et le Shinkansen', txt: "Le réseau est méthodique une fois qu'on en a la clé : lignes couleur, correspondances fléchées, quais numérotés. Le Shinkansen relie les grandes villes à plus de 300 km/h, avec une ponctualité devenue légendaire. Nous vous expliquons comment réserver, où vous placer sur le quai, et comment enchaîner les correspondances sans stress." },
      { t: 'La carte Suica', txt: "Une carte, et le quotidien japonais s'ouvre : métro, bus, trains, distributeurs, konbini, casiers à bagages. On la charge en quelques secondes à une borne et on avance. Nous vous la préparons dès votre arrivée." },
      { t: 'Les baguettes', txt: "Les tenir n'est pas si difficile ; les bons réflexes le sont un peu plus. Ne jamais les planter debout dans le riz, ne jamais se les passer de main à main, ne jamais pointer avec. Quelques règles simples, et un repas qui se passe sans accroc." },
    ],
    dejaEnPlace: 'Déjà en place sur le site : JR Pass · Takkyubin · saisons · budget',
    langueEyebrow: 'LANGUE',
    langueTitre: 'Deux alphabets, quinze kanji, trente phrases.',
    langueKicker: '· de quoi lire une enseigne et commander un repas.',
    hiragana: 'Hiragana',
    katakana: 'Katakana',
    katakanaNote: 'Mêmes sons, alphabet différent, utilisé pour les mots étrangers et les enseignes.',
    kanjiTitre: 'Quinze kanji utiles au voyage',
    thKanji: 'Kanji',
    thLecture: 'Lecture',
    thSens: 'Sens',
    phrasesTitre: 'Une trentaine de phrases utiles',
    thLangue: 'Français',
    thJaponais: 'Japonais (romaji)',
    kanji: [
      ['日', 'hi / nichi', 'jour, soleil'],
      ['本', 'hon', 'origine, livre (日本 = Japon)'],
      ['人', 'hito / jin', 'personne'],
      ['大', 'dai / oo', 'grand'],
      ['小', 'shou / chii', 'petit'],
      ['中', 'chuu / naka', 'milieu, dans'],
      ['出', 'shutsu / de', 'sortie, sortir'],
      ['入', 'nyuu / hai', 'entrée, entrer'],
      ['口', 'kuchi / kou', 'ouverture (出口 = sortie)'],
      ['駅', 'eki', 'gare'],
      ['円', 'en', 'yen'],
      ['山', 'yama / san', 'montagne'],
      ['川', 'kawa', 'rivière'],
      ['東', 'higashi / tou', 'est (東京 = Tokyo)'],
      ['京', 'kyou', 'capitale (京都 = Kyoto)'],
    ],
    phrases: [
      ['Bonjour', 'Konnichiwa'],
      ['Bonsoir', 'Konbanwa'],
      ['Au revoir', 'Sayonara'],
      ['Merci', 'Arigatou gozaimasu'],
      ['Merci beaucoup', 'Doumo arigatou gozaimasu'],
      ["S'il vous plaît", 'Onegaishimasu'],
      ['Excusez-moi, pardon', 'Sumimasen'],
      ['Oui', 'Hai'],
      ['Non', 'Iie'],
      ['Je ne comprends pas', 'Wakarimasen'],
      ['Parlez-vous français / anglais ?', 'Furansugo / Eigo o hanasemasu ka'],
      ['Combien ça coûte ?', 'Ikura desu ka'],
      ['Où sont les toilettes ?', 'Toire wa doko desu ka'],
      ["L'addition, s'il vous plaît", 'Okaikei onegaishimasu'],
      ["C'est délicieux", 'Oishii desu'],
      ['Une / deux / trois personnes', 'Hitori / Futari / San-nin'],
      ['Je voudrais…', '… o kudasai'],
      ['Sans (ingrédient, allergie)', '… nashi de'],
      ['Où est la gare ?', 'Eki wa doko desu ka'],
      ['À quelle heure part le train ?', 'Densha wa nanji ni demasu ka'],
      ['Je suis perdu', 'Michi ni mayoimashita'],
      ["Pouvez-vous m'aider ?", 'Tetsudatte moraemasu ka'],
      ["C'est combien jusqu'à… ?", '… made ikura desu ka'],
      ['Un billet pour…', '… made no kippu o kudasai'],
      ['Où puis-je acheter… ?', '… wa doko de kaemasu ka'],
      ['Je suis allergique à…', '… arerugii ga arimasu'],
      ['Au secours', 'Tasukete'],
      ['Appelez une ambulance', 'Kyuukyuusha o yonde kudasai'],
      ["Où est l'hôpital ?", 'Byouin wa doko desu ka'],
      ['Avant de manger', 'Itadakimasu'],
      ['Après avoir mangé', 'Gochisousama deshita'],
    ],
  },
};
