// El Japon (hub, historia, gastronomia) y guia practica.
// Version espanola, traducida de japon.fr.js.
export default {
  hub: {
    eyebrow: 'EL JAPÓN',
    titre: 'El país antes del viaje.',
    lede: 'Dos entradas para entender adónde va usted: las eras que dieron forma al país, y la cocina que cuenta su geografía, prefectura a prefectura.',
    sousPage: 'SUBPÁGINA',
    histoireTitre: 'Historia',
    histoireTexte: 'El Japón no se cuenta como una línea recta. Es una sucesión de eras, algunas fundadoras, otras simplemente tranquilas. Solo contamos las que de verdad dieron forma al país que usted va a visitar.',
    gastroTitre: 'Gastronomía',
    gastroTexte: 'El Japón no se come de la misma manera de un extremo a otro del archipiélago. Cada prefectura tiene sus productos, sus técnicas, sus platos que solo se encuentran aquí.',
    photo: 'Foto',
  },

  histoire: {
    eyebrow: 'EL JAPÓN · HISTORIA',
    titre: 'Tres eras, y el país que usted va a visitar.',
    lede: 'El Japón no se cuenta como una línea recta. Es una sucesión de eras, algunas fundadoras, otras simplemente tranquilas. Solo contamos las que de verdad dieron forma al país que usted va a visitar.',
    aParaitre: 'PRÓXIMAMENTE',
    eres: [
      { nom: 'Heian', annees: '794 · 1185', sur: 'La corte de Kioto',
        txt: 'La capital se traslada a Kioto. Durante cuatro siglos, una aristocracia refinada inventa buena parte de la estética japonesa: la literatura de corte, el culto a la estación, un sentido de la belleza que nunca ha abandonado del todo el país.' },
      { nom: 'Edo', annees: '1603 · 1868', sur: 'La paz de los Tokugawa',
        txt: 'Doscientos cincuenta años de paz impuesta por los shogunes Tokugawa, un país cerrado sobre sí mismo, y el auge de una cultura urbana y mercantil: la estampa, el kabuki, las grandes rutas como el Nakasendo que todavía hoy se recorre.' },
      { nom: 'Meiji', annees: '1868 · 1912', sur: 'La apertura',
        txt: 'El país se abre por la fuerza al comercio occidental y luego se moderniza a una velocidad inédita: industria, ejército, instituciones occidentales, sin dejar de mantener al emperador como figura central.' },
    ],
    reserve: [
      'Los orígenes, hasta el siglo VII',
      'Nara y la llegada del budismo',
      'Kamakura, los primeros shogunes',
      'Muromachi, la edad de las guerras',
      'Guerra y reconstrucción',
      'El Japón contemporáneo',
    ],
  },

  gastronomie: {
    eyebrow: 'EL JAPÓN · GASTRONOMÍA',
    titre: 'La geografía contada en el plato.',
    lede: 'El Japón no se come de la misma manera de un extremo a otro del archipiélago. Cada prefectura tiene sus productos, sus técnicas, sus platos que solo se encuentran aquí. Esta página se construye prefectura a prefectura, al hilo de nuestros viajes y de nuestros encuentros con los productores y los cocineros.',
    photoDe: 'Foto, cocina de',
    prefectures: [
      { nom: 'Tokio', num: 'Prefectura 13',
        txt: 'La capital inventó el sushi tal como lo conocemos hoy: el Edomae, nacido en los muelles de la bahía de Edo, pensado para comerse deprisa y de pie. También está el tempura, la fritura ligera llegada del siglo XVI, la anguila a la parrilla (unagi) y el soba, el fideo de trigo sarraceno de los artesanos de Edo. Tokio es una ciudad de especialistas: un restaurante, un plato, toda una vida dedicada a perfeccionarlo.' },
      { nom: 'Kioto', num: 'Prefectura 26',
        txt: 'Antigua capital imperial, Kioto dio origen al kaiseki, la comida de varios servicios que sigue las estaciones al pie de la letra. La ciudad vive también de su tofu, célebre por la pureza de su agua, de su cocina vegetariana de los templos budistas (shojin ryori) y de su obanzai, la cocina familiar kiotense, discreta y nunca despilfarrada. Es, en fin, la capital del té y de los wagashi, los dulces pensados para acompañarlo.' },
      { nom: 'Osaka', num: 'Prefectura 27',
        txt: 'Osaka se llama a sí misma « la cocina del país » (tenka no daidokoro). Ciudad mercantil, ha hecho de la calle su mesa: takoyaki (bolitas de pulpo), okonomiyaki (torta con guarnición), kushikatsu (brochetas rebozadas). Una cocina generosa, popular, pensada para compartirse entre amigos, en las antípodas de la contención de Kioto, a unas pocas decenas de kilómetros.' },
    ],
    suite: 'Las otras cuarenta y cuatro prefecturas se irán sumando al hilo de los viajes. Cada ficha parte de un productor, de un cocinero, o de un plato que no se encuentra en ningún otro sitio.',
    compteur: '3 / 47 publicadas',
  },

  guide: {
    eyebrow: 'GUÍA PRÁCTICA',
    titre: 'La caja de herramientas del viaje.',
    lede: 'Los transportes, la tarjeta Suica, los usos de mesa, y con qué descifrar un rótulo. Lo que hay que saber antes de partir, y lo que le preparamos sobre el terreno.',
    blocs: [
      { t: 'El metro y el Shinkansen', txt: 'La red es metódica en cuanto se tiene la clave: líneas por colores, correspondencias señalizadas, andenes numerados. El Shinkansen une las grandes ciudades a más de 300 km/h, con una puntualidad ya legendaria. Le explicamos cómo reservar, dónde colocarse en el andén y cómo encadenar las correspondencias sin estrés.' },
      { t: 'La tarjeta Suica', txt: 'Una tarjeta, y el día a día japonés se abre: metro, autobuses, trenes, máquinas expendedoras, konbini, taquillas de equipaje. Se recarga en unos segundos en un terminal y se sigue adelante. Se la preparamos nada más llegar.' },
      { t: 'Los palillos', txt: 'Sostenerlos no es tan difícil; los buenos reflejos lo son algo más. Nunca clavarlos de pie en el arroz, nunca pasárselos de mano a mano, nunca señalar con ellos. Unas cuantas reglas sencillas, y una comida que transcurre sin tropiezos.' },
    ],
    dejaEnPlace: 'Ya disponible en el sitio: JR Pass · Takkyubin · estaciones · presupuesto',
    langueEyebrow: 'LENGUA',
    langueTitre: 'Dos alfabetos, quince kanji, treinta frases.',
    langueKicker: '· con qué leer un rótulo y pedir una comida.',
    hiragana: 'Hiragana',
    katakana: 'Katakana',
    katakanaNote: 'Mismos sonidos, alfabeto distinto, usado para las palabras extranjeras y los rótulos.',
    kanjiTitre: 'Quince kanji útiles para el viaje',
    thKanji: 'Kanji',
    thLecture: 'Lectura',
    thSens: 'Sentido',
    phrasesTitre: 'Una treintena de frases útiles',
    thLangue: 'Español',
    thJaponais: 'Japonés (romaji)',
    kanji: [
      ['日', 'hi / nichi', 'día, sol'],
      ['本', 'hon', 'origen, libro (日本 = Japón)'],
      ['人', 'hito / jin', 'persona'],
      ['大', 'dai / oo', 'grande'],
      ['小', 'shou / chii', 'pequeño'],
      ['中', 'chuu / naka', 'medio, dentro'],
      ['出', 'shutsu / de', 'salida, salir'],
      ['入', 'nyuu / hai', 'entrada, entrar'],
      ['口', 'kuchi / kou', 'abertura (出口 = salida)'],
      ['駅', 'eki', 'estación'],
      ['円', 'en', 'yen'],
      ['山', 'yama / san', 'montaña'],
      ['川', 'kawa', 'río'],
      ['東', 'higashi / tou', 'este (東京 = Tokio)'],
      ['京', 'kyou', 'capital (京都 = Kioto)'],
    ],
    phrases: [
      ['Buenos días', 'Konnichiwa'],
      ['Buenas noches', 'Konbanwa'],
      ['Adiós', 'Sayonara'],
      ['Gracias', 'Arigatou gozaimasu'],
      ['Muchas gracias', 'Doumo arigatou gozaimasu'],
      ['Por favor', 'Onegaishimasu'],
      ['Perdone, disculpe', 'Sumimasen'],
      ['Sí', 'Hai'],
      ['No', 'Iie'],
      ['No entiendo', 'Wakarimasen'],
      ['¿Habla español / inglés?', 'Supeingo / Eigo o hanasemasu ka'],
      ['¿Cuánto cuesta?', 'Ikura desu ka'],
      ['¿Dónde están los servicios?', 'Toire wa doko desu ka'],
      ['La cuenta, por favor', 'Okaikei onegaishimasu'],
      ['Está delicioso', 'Oishii desu'],
      ['Una / dos / tres personas', 'Hitori / Futari / San-nin'],
      ['Quisiera…', '… o kudasai'],
      ['Sin (ingrediente, alergia)', '… nashi de'],
      ['¿Dónde está la estación?', 'Eki wa doko desu ka'],
      ['¿A qué hora sale el tren?', 'Densha wa nanji ni demasu ka'],
      ['Me he perdido', 'Michi ni mayoimashita'],
      ['¿Puede ayudarme?', 'Tetsudatte moraemasu ka'],
      ['¿Cuánto cuesta hasta…?', '… made ikura desu ka'],
      ['Un billete para…', '… made no kippu o kudasai'],
      ['¿Dónde puedo comprar…?', '… wa doko de kaemasu ka'],
      ['Soy alérgico a…', '… arerugii ga arimasu'],
      ['Socorro', 'Tasukete'],
      ['Llame a una ambulancia', 'Kyuukyuusha o yonde kudasai'],
      ['¿Dónde está el hospital?', 'Byouin wa doko desu ka'],
      ['Antes de comer', 'Itadakimasu'],
      ['Después de comer', 'Gochisousama deshita'],
    ],
  },
};
