// Japan (hub, history, gastronomy) and practical guide.
// English version, translated from the French reference.
export default {
  hub: {
    eyebrow: 'JAPAN',
    titre: 'The country before the journey.',
    lede: "Two ways in to understand where you are going: the eras that shaped the country, and the cooking that tells its geography, prefecture by prefecture.",
    sousPage: 'SUB-PAGE',
    histoireTitre: 'History',
    histoireTexte: "Japan does not unfold in a straight line. It is a succession of eras, some of them founding moments, others simply quiet. We tell only those that truly shaped the country you are about to visit.",
    gastroTitre: 'Gastronomy',
    gastroTexte: "Japan is not eaten the same way from one end of the archipelago to the other. Each prefecture has its own produce, its own techniques, its own dishes found nowhere else.",
    photo: 'Photo',
  },

  histoire: {
    eyebrow: 'JAPAN · HISTORY',
    titre: 'Three eras, and the country you are about to visit.',
    lede: "Japan does not unfold in a straight line. It is a succession of eras, some of them founding moments, others simply quiet. We tell only those that truly shaped the country you are about to visit.",
    aParaitre: 'FORTHCOMING',
    eres: [
      { nom: 'Heian', annees: '794 · 1185', sur: 'The court of Kyoto',
        txt: "The capital moves to Kyoto. For four centuries, a refined aristocracy invents a great deal of Japanese aesthetics: court literature, the cult of the season, a sense of beauty that has never really left the country." },
      { nom: 'Edo', annees: '1603 · 1868', sur: 'The Tokugawa peace',
        txt: "Two hundred and fifty years of peace imposed by the Tokugawa shoguns, a country closed in on itself, and the rise of an urban, merchant culture: the woodblock print, kabuki theatre, and the great highways such as the Nakasendo, still walked today." },
      { nom: 'Meiji', annees: '1868 · 1912', sur: 'The opening',
        txt: "The country is forced open to Western trade, then modernises at an unprecedented pace: industry, army, Western institutions, all while keeping the emperor as its central figure." },
    ],
    reserve: [
      'The origins, up to the seventh century',
      'Nara and the arrival of Buddhism',
      'Kamakura, the first shoguns',
      'Muromachi, the age of wars',
      'War and reconstruction',
      'Contemporary Japan',
    ],
  },

  gastronomie: {
    eyebrow: 'JAPAN · GASTRONOMY',
    titre: 'Geography told on the plate.',
    lede: "Japan is not eaten the same way from one end of the archipelago to the other. Each prefecture has its own produce, its own techniques, its own dishes found nowhere else. This page is built prefecture by prefecture, as our travels and our encounters with producers and cooks unfold.",
    photoDe: 'Photo, cooking of',
    prefectures: [
      { nom: 'Tokyo', num: 'Prefecture 13',
        txt: "The capital invented sushi as we know it today: Edomae, born on the quays of Edo Bay, designed to be eaten quickly and standing up. It is also home to tempura, the light batter frying that arrived in the sixteenth century, to grilled eel (unagi) and to soba, the buckwheat noodle of the Edo artisans. Tokyo is a city of specialists: one restaurant, one dish, a whole lifetime spent perfecting it." },
      { nom: 'Kyoto', num: 'Prefecture 26',
        txt: "The former imperial capital gave birth to kaiseki, the multi-course meal that follows the seasons to the letter. The city also lives on its tofu, prized for the purity of its water, on the vegetarian cooking of its Buddhist temples (shojin ryori), and on its obanzai, the Kyoto home cooking, understated and never wasteful. It is, finally, the capital of tea and of wagashi, the sweets conceived to accompany it." },
      { nom: 'Osaka', num: 'Prefecture 27',
        txt: "Osaka calls itself “the nation’s kitchen” (tenka no daidokoro). A merchant city, it has made the street its table: takoyaki (octopus balls), okonomiyaki (savoury filled pancake), kushikatsu (breaded skewers). Generous, popular cooking, meant to be shared among friends, the opposite of Kyoto’s restraint a few dozen kilometres away." },
    ],
    suite: "The other forty-four prefectures will be added as we travel. Each entry starts with a producer, a cook, or a dish found nowhere else.",
    compteur: '3 / 47 published',
  },

  guide: {
    eyebrow: 'PRACTICAL GUIDE',
    titre: 'The travel toolkit.',
    lede: "Transport, the Suica card, table manners, and enough to decipher a shop sign. What you need to know before you leave, and what we prepare for you on arrival.",
    blocs: [
      { t: 'The metro and the Shinkansen', txt: "The network is methodical once you have the key to it: colour-coded lines, arrowed interchanges, numbered platforms. The Shinkansen links the major cities at more than 300 km/h, with a punctuality that has become legendary. We explain how to book, where to stand on the platform, and how to string connections together without stress." },
      { t: 'The Suica card', txt: "One card, and Japanese daily life opens up: metro, buses, trains, vending machines, konbini, luggage lockers. You top it up at a machine in seconds and off you go. We have it ready for you the moment you arrive." },
      { t: 'Chopsticks', txt: "Holding them is not so difficult; the right reflexes are a little harder. Never stand them upright in the rice, never pass food from hand to hand with them, never point with them. A few simple rules, and a meal that passes without a hitch." },
    ],
    dejaEnPlace: 'Already on the site: JR Pass · Takkyubin · seasons · budget',
    langueEyebrow: 'LANGUAGE',
    langueTitre: 'Two alphabets, fifteen kanji, thirty phrases.',
    langueKicker: '· enough to read a sign and order a meal.',
    hiragana: 'Hiragana',
    katakana: 'Katakana',
    katakanaNote: 'Same sounds, different alphabet, used for foreign words and shop signs.',
    kanjiTitre: 'Fifteen kanji useful when travelling',
    thKanji: 'Kanji',
    thLecture: 'Reading',
    thSens: 'Meaning',
    phrasesTitre: 'Around thirty useful phrases',
    thLangue: 'English',
    thJaponais: 'Japanese (romaji)',
    kanji: [
      ['日', 'hi / nichi', 'day, sun'],
      ['本', 'hon', 'origin, book (日本 = Japan)'],
      ['人', 'hito / jin', 'person'],
      ['大', 'dai / oo', 'large'],
      ['小', 'shou / chii', 'small'],
      ['中', 'chuu / naka', 'middle, inside'],
      ['出', 'shutsu / de', 'exit, to go out'],
      ['入', 'nyuu / hai', 'entrance, to enter'],
      ['口', 'kuchi / kou', 'opening (出口 = exit)'],
      ['駅', 'eki', 'station'],
      ['円', 'en', 'yen'],
      ['山', 'yama / san', 'mountain'],
      ['川', 'kawa', 'river'],
      ['東', 'higashi / tou', 'east (東京 = Tokyo)'],
      ['京', 'kyou', 'capital (京都 = Kyoto)'],
    ],
    phrases: [
      ['Good morning, good afternoon', 'Konnichiwa'],
      ['Good evening', 'Konbanwa'],
      ['Goodbye', 'Sayonara'],
      ['Thank you', 'Arigatou gozaimasu'],
      ['Thank you very much', 'Doumo arigatou gozaimasu'],
      ['Please', 'Onegaishimasu'],
      ['Excuse me, sorry', 'Sumimasen'],
      ['Yes', 'Hai'],
      ['No', 'Iie'],
      ['I do not understand', 'Wakarimasen'],
      ['Do you speak English?', 'Eigo o hanasemasu ka'],
      ['How much is it?', 'Ikura desu ka'],
      ['Where are the toilets?', 'Toire wa doko desu ka'],
      ['The bill, please', 'Okaikei onegaishimasu'],
      ['It is delicious', 'Oishii desu'],
      ['One / two / three people', 'Hitori / Futari / San-nin'],
      ['I would like…', '… o kudasai'],
      ['Without (ingredient, allergy)', '… nashi de'],
      ['Where is the station?', 'Eki wa doko desu ka'],
      ['What time does the train leave?', 'Densha wa nanji ni demasu ka'],
      ['I am lost', 'Michi ni mayoimashita'],
      ['Could you help me?', 'Tetsudatte moraemasu ka'],
      ['How much is it to…?', '… made ikura desu ka'],
      ['A ticket to…', '… made no kippu o kudasai'],
      ['Where can I buy…?', '… wa doko de kaemasu ka'],
      ['I am allergic to…', '… arerugii ga arimasu'],
      ['Help', 'Tasukete'],
      ['Call an ambulance', 'Kyuukyuusha o yonde kudasai'],
      ['Where is the hospital?', 'Byouin wa doko desu ka'],
      ['Before eating', 'Itadakimasu'],
      ['After eating', 'Gochisousama deshita'],
    ],
  },
};
