// Nuestro enfoque, contacto y diario. Versión en español de España, traducida de pages.fr.js.
export default {
  about: {
    eyebrow: 'NUESTRO ENFOQUE',
    titre: 'No hacemos turismo. Damos a conocer el Japón auténtico.',
    lede: 'Kiraku, 喜楽, es « alegría » y « soltura », una junto a otra. No es un eslogan: es nuestra única regla de trabajo.',
    banniere: 'Foto ancha, paisaje o callejón',
    sommaire: 'Índice',
    toc: ['01 · Por qué Kiraku', '02 · Cómo trabajamos', '03 · Quiénes somos', '04 · Lo que no hacemos'],
    h1: '01 · Por qué Kiraku.',
    p1: 'Conoce la sensación: vuelve de tres semanas en Japón y tiene la impresión de no haber visto a nadie. Demasiadas estaciones, demasiadas pantallas, demasiados algoritmos. Kiraku nació de ese sentimiento.',
    p2: 'No le prometemos un Japón secreto. Japón no necesita estar escondido para vivirse de otra manera. Le llevamos a lugares insólitos, le hacemos comer donde comen los propios japoneses y visitamos al amanecer, antes que los grupos.',
    h2: '02 · Cómo trabajamos.',
    p3: 'Cada itinerario se prueba en persona antes de ofrecerlo. Si no hemos dormido allí nosotros mismos, no lo vendemos. Es lento. Para nosotros, es caro. Pero es la única manera de garantizar que Hirosan seguirá allí y que preparará el desayuno a las siete.',
    chiffresEyebrow: 'EN CIFRAS',
    chiffres: [
      { n: '20', t: 'años, o casi, dedicados a Japón' },
      { n: '10', t: 'años, como mínimo, guiando en Japón' },
      { n: '8', t: 'viajeros como máximo, tanto en privado como en grupo' },
    ],
    h4: 'Lo que no hacemos.',
    liste: [
      'Los autocares turísticos. Ocho personas como máximo, tanto en privado como en grupo.',
      'Los ryokan que han conservado el nombre pero sirven el desayuno en bufé.',
      'Las visitas en grupo, a las horas en que visita todo el mundo.',
      'Los itinerarios « llave en mano » sin una llamada previa.',
      'Los pagos aplazados sin hablar antes de su presupuesto real.',
    ],
  },

  contact: {
    eyebrow: 'ESCRÍBANOS',
    titre: 'Treinta minutos por teléfono, sin compromiso.',
    lede: 'Cuéntenos qué le apetece. Le respondemos en un plazo de dos días laborables, con una propuesta de horario para una llamada.',
    prenom: 'Nombre',
    prenomPh: 'Camille',
    nom: 'Apellidos',
    nomPh: 'Aoyama',
    email: 'Email',
    emailPh: 'camille@exemple.com',
    emailAide: 'Guardamos su dirección para usted. Ni venta a terceros, ni boletín sin su consentimiento.',
    tel: 'Teléfono móvil',
    telPh: '06 45 78 21 09',
    telAide: 'Un móvil, francés o extranjero en formato +33 6 45 78 21 09. Para la llamada, nada más.',
    qui: 'Quién viaja',
    adultes: 'Adultos',
    adultesSub: '13 años o más',
    enfants: 'Niños',
    enfantsSub: 'menos de 13 años',
    chambres: 'Habitaciones',
    chambresAuto: 'dos por habitación',
    chambresManuel: 'a su petición',
    mois: 'Mes deseado',
    moisPh: 'Elegir un mes',
    moisOptions: ['Abril, sakura', 'Mayo, principio del verano', 'Septiembre, después de las lluvias', 'Octubre, momiji', 'Enero, nieve', 'Aún sin decidir'],
    duree: 'Duración prevista',
    dureePh: 'Elegir',
    dureeOptions: ['3 a 5 noches', '6 a 10 noches', '2 semanas o más'],
    message: 'Lo que le apetece',
    messagePh: 'Onsen, senderismo, cocina, artesanía, calma, nada… cuéntenoslo.',
    messageAide: 'Cuanto más concreto sea, mejor podremos ayudarle. Incluso « no lo sé » es una buena respuesta.',
    news: 'También puede escribirme cuatro veces al año con sus cuadernos de viaje y los nuevos itinerarios.',
    merciTitre: 'Tomamos nota.',
    merciTexte: 'Le respondemos en un plazo de dos días laborables con una propuesta de horario. Mientras tanto, eche un vistazo al diario, hay cosas que solo contamos por escrito.',
    merciBouton: 'Enviar otra solicitud',
    asideTitre: 'Otras formas de contactar con nosotros.',
    parTelephone: 'Por teléfono',
    horaires: 'Lun a sáb, de 10 a 18 h (Paris)',
    parEmail: 'Por email',
    auBureau: 'En la oficina',
    adresse: '47 rue Vivienne',
    adresse2: '75002 Paris',
    adresse3: 'con cita previa',
    carnet: 'Nuestro cuaderno',
    carnetTexte: 'en Instagram, fotos tomadas durante los viajes de reconocimiento.',
  },

  journal: {
    eyebrow: 'EL DIARIO',
    titre: 'Lo que anotamos al volver.',
    lede: 'Cuadernos de viaje, mapas dibujados a mano y, de vez en cuando, alguna queja sobre las guías de plástico. Una publicación cada tres semanas aproximadamente.',
    posts: [
      { eyebrow: 'CUADERNO · MAYO DE 2026', title: 'Tres días sin teléfono en Yakushima.', kicker: 'Y lo que perdimos por el camino.' },
      { eyebrow: 'CUADERNO · MARZO DE 2026', title: 'Cómo elegimos un ryokan.', kicker: 'o más bien, cómo Hiroko-san eligió por nosotros.' },
      { eyebrow: 'CUADERNO · FEBRERO DE 2026', title: 'El kissaten de antes de la guerra de Mori-san, 47 años después.', kicker: 'Volvimos allí una tercera vez.' },
      { eyebrow: 'CUADERNO · NOVIEMBRE DE 2025', title: 'Momiji: por qué octubre es demasiado pronto.', kicker: 'Y por qué ahora lo programamos en noviembre.' },
    ],
  },

  cgv: {
    eyebrowVersion: 'Condiciones generales de venta',
    titre: 'Lo que nos comprometemos a hacer y lo que le pedimos.',
    sousTitre: (v) => `Kiraku Travel, la alegría de la soltura (喜楽). En vigor a partir del ${v.vigueur}. Este documento anula y sustituye a la versión del ${v.remplace}.`,
    preambule: 'Preámbulo · identificación del operador',
    sommaire: 'Índice',
    question: '¿Alguna pregunta? Escríbanos',
    pied: (v) => `${v.label} · en vigor el ${v.vigueur}.`,
    primaute: 'Esta es una traducción de cortesía. Solo la versión francesa de estas condiciones tiene valor contractual.',
  },
};
