// Notre approche, contact et journal. Version francaise, reference des traductions.
export default {
  about: {
    eyebrow: 'NOTRE APPROCHE',
    titre: 'On ne fait pas de tourisme. On fait découvrir le Japon authentique.',
    lede: "Kiraku, 喜楽, c'est « joie » et « aise », côte à côte. Pas un slogan : c'est notre seule règle de travail.",
    banniere: 'Photo large, paysage ou ruelle',
    sommaire: 'Sommaire',
    toc: ['01 · Pourquoi Kiraku', '02 · Comment on travaille', '03 · Qui on est', "04 · Ce qu'on ne fait pas"],
    h1: '01 · Pourquoi Kiraku.',
    p1: "Vous connaissez l'effet : vous rentrez de trois semaines au Japon, et vous avez l'impression de n'avoir vu personne. Trop de gares, trop d'écrans, trop d'algorithmes. Kiraku est né de ce sentiment.",
    p2: "On ne vous promet pas un Japon secret. Le Japon n'a pas besoin d'être caché pour être vécu autrement. On vous emmène dans des lieux insolites, on vous fait manger là où les Japonais eux-mêmes vont manger, et on visite au lever du jour, avant les groupes.",
    h2: '02 · Comment on travaille.',
    p3: "Chaque itinéraire est testé en personne avant d'être proposé. Si on n'y a pas dormi nous-mêmes, on ne le vend pas. C'est lent. C'est cher, pour nous. Mais c'est la seule façon de garantir qu'Hirosan sera toujours là, et qu'elle préparera le petit-déjeuner à sept heures.",
    chiffresEyebrow: 'EN CHIFFRES',
    chiffres: [
      { n: '20', t: 'ans, ou presque, tournés vers le Japon' },
      { n: '10', t: 'ans, au moins, à guider le Japon' },
      { n: '8', t: 'voyageurs au maximum, en privé comme en groupe' },
    ],
    h4: "Ce qu'on ne fait pas.",
    liste: [
      'Les cars de tourisme. Huit personnes au maximum, en privé comme en groupe.',
      'Les ryokan qui ont gardé le nom mais qui servent leur petit-déjeuner en buffet.',
      'Les visites en groupe, aux heures où tout le monde visite.',
      'Les itinéraires « clé en main » sans appel préalable.',
      'Les paiements en plusieurs fois sans discussion sur votre budget réel.',
    ],
  },

  contact: {
    eyebrow: 'NOUS ÉCRIRE',
    titre: 'Trente minutes au téléphone, sans engagement.',
    lede: "Dites-nous ce qui vous tente. On revient vers vous sous deux jours ouvrés, avec une proposition d'horaire pour un appel.",
    prenom: 'Prénom',
    prenomPh: 'Camille',
    nom: 'Nom',
    nomPh: 'Aoyama',
    email: 'Email',
    emailPh: 'camille@exemple.com',
    emailAide: "On garde votre adresse pour vous. Pas de revente, pas de newsletter sans accord.",
    tel: 'Téléphone portable',
    telPh: '06 45 78 21 09',
    telAide: "Un mobile, français ou étranger au format +33 6 45 78 21 09. Pour l'appel, rien d'autre.",
    qui: 'Qui voyage',
    adultes: 'Adultes',
    adultesSub: '13 ans et plus',
    enfants: 'Enfants',
    enfantsSub: 'moins de 13 ans',
    chambres: 'Chambres',
    chambresAuto: 'deux par chambre',
    chambresManuel: 'à votre demande',
    mois: 'Mois souhaité',
    moisPh: 'Choisir un mois',
    moisOptions: ['Avril, sakura', "Mai, début d'été", 'Septembre, après les pluies', 'Octobre, momiji', 'Janvier, neige', 'Pas encore décidé'],
    duree: 'Durée envisagée',
    dureePh: 'Choisir',
    dureeOptions: ['3 – 5 nuits', '6 – 10 nuits', '2 semaines ou plus'],
    message: 'Ce qui vous tente',
    messagePh: 'Onsen, randonnée, cuisine, artisanat, calme, rien… racontez-nous.',
    messageAide: "Plus c'est précis, mieux on peut vous aider. Même « je ne sais pas » est une bonne réponse.",
    news: "Vous pouvez aussi m'écrire quatre fois par an avec vos carnets de voyage et les nouveaux itinéraires.",
    merciTitre: "C'est noté.",
    merciTexte: "On revient vers vous sous deux jours ouvrés avec une proposition d'horaire. En attendant, jetez un œil au journal, il y a des choses qu'on ne dit qu'à l'écrit.",
    merciBouton: 'Envoyer une autre demande',
    asideTitre: 'Autres façons de nous joindre.',
    parTelephone: 'Par téléphone',
    horaires: 'Lun–sam, 10 h – 18 h (Paris)',
    parEmail: 'Par email',
    auBureau: 'Au bureau',
    adresse: '47 rue Vivienne',
    adresse2: '75002 Paris',
    adresse3: 'sur rendez-vous',
    carnet: 'Notre carnet',
    carnetTexte: 'sur Instagram, photos prises pendant les repérages.',
  },

  journal: {
    eyebrow: 'LE JOURNAL',
    titre: "Ce qu'on note quand on rentre.",
    lede: "Des carnets de voyage, des cartes dessinées à la main, et de temps en temps un coup de gueule sur les guides en plastique. Une parution toutes les trois semaines environ.",
    posts: [
      { eyebrow: 'CARNET · MAI 2026', title: 'Trois jours sans téléphone à Yakushima.', kicker: "Et ce qu'on a perdu en route." },
      { eyebrow: 'CARNET · MARS 2026', title: 'Comment on choisit un ryokan.', kicker: 'ou plutôt, comment Hiroko-san a choisi pour nous.' },
      { eyebrow: 'CARNET · FÉVRIER 2026', title: "Le kissaten d'avant-guerre de Mori-san, 47 ans plus tard.", kicker: 'On y est retourné une troisième fois.' },
      { eyebrow: 'CARNET · NOVEMBRE 2025', title: 'Momiji : pourquoi octobre est trop tôt.', kicker: 'Et pourquoi on programme désormais en novembre.' },
    ],
  },

  cgv: {
    eyebrowVersion: 'Conditions générales de vente',
    titre: "Ce que l'on s'engage à faire, et ce que l'on vous demande.",
    sousTitre: (v) => `Kiraku Travel, la joie de l'aisance (喜楽). En vigueur à compter du ${v.vigueur}. Ce document annule et remplace la version du ${v.remplace}.`,
    preambule: "Préambule · identification de l'opérateur",
    sommaire: 'Sommaire',
    question: 'Une question ? Écrivez-nous',
    pied: (v) => `${v.label} · en vigueur au ${v.vigueur}.`,
    primaute: null,
  },
};
