// Our approach, contact and journal. British English version, translated from pages.fr.js.
export default {
  about: {
    eyebrow: 'OUR APPROACH',
    titre: 'We do not do tourism. We help you discover the real Japan.',
    lede: 'Kiraku, 喜楽, is “joy” and “ease”, side by side. Not a slogan: it is our only working rule.',
    banniere: 'Wide photo, landscape or lane',
    sommaire: 'Contents',
    toc: ['01 · Why Kiraku', '02 · How we work', '03 · Who we are', '04 · What we do not do'],
    h1: '01 · Why Kiraku.',
    p1: 'You know the feeling: you come home from three weeks in Japan and you have the impression that you met no one. Too many stations, too many screens, too many algorithms. Kiraku was born of that feeling.',
    p2: 'We are not promising you a secret Japan. Japan does not need to be hidden to be lived differently. We take you to out of the way places, we sit you down where Japanese people themselves eat, and we visit at first light, before the groups.',
    h2: '02 · How we work.',
    p3: 'Every itinerary is tested in person before we offer it. If we have not slept there ourselves, we do not sell it. It is slow. It is expensive, for us. But it is the only way to guarantee that Hirosan will still be there, and that she will be making breakfast at seven.',
    chiffresEyebrow: 'IN NUMBERS',
    chiffres: [
      { n: '20', t: 'years, or nearly, turned towards Japan' },
      { n: '10', t: 'years, at least, guiding in Japan' },
      { n: '8', t: 'travellers at most, in private as in a group' },
    ],
    h4: 'What we do not do.',
    liste: [
      'Coach tours. Eight people at most, in private as in a group.',
      'Ryokan that have kept the name but serve their breakfast as a buffet.',
      'Group visits, at the hours when everybody visits.',
      '“Turnkey” itineraries with no prior phone call.',
      'Payment in instalments with no discussion of your real budget.',
    ],
  },

  contact: {
    eyebrow: 'WRITE TO US',
    titre: 'Thirty minutes on the phone, with no commitment.',
    lede: 'Tell us what appeals to you. We come back to you within two working days, with a suggested time for a call.',
    prenom: 'First name',
    prenomPh: 'Camille',
    nom: 'Surname',
    nomPh: 'Aoyama',
    email: 'Email',
    emailPh: 'camille@exemple.com',
    emailAide: 'We keep your address to ourselves. No reselling, no newsletter without your consent.',
    tel: 'Mobile number',
    telPh: '06 45 78 21 09',
    telAide: 'A mobile, French or foreign in the format +33 6 45 78 21 09. For the call, nothing else.',
    qui: 'Who is travelling',
    adultes: 'Adults',
    adultesSub: '13 and over',
    enfants: 'Children',
    enfantsSub: 'under 13',
    chambres: 'Rooms',
    chambresAuto: 'two per room',
    chambresManuel: 'as you ask',
    mois: 'Preferred month',
    moisPh: 'Choose a month',
    moisOptions: ['April, sakura', 'May, early summer', 'September, after the rains', 'October, momiji', 'January, snow', 'Not decided yet'],
    duree: 'Length of stay',
    dureePh: 'Choose',
    dureeOptions: ['3 to 5 nights', '6 to 10 nights', '2 weeks or more'],
    message: 'What appeals to you',
    messagePh: 'Onsen, walking, food, craft, quiet, nothing at all… tell us about it.',
    messageAide: 'The more precise you are, the better we can help you. Even “I do not know” is a good answer.',
    news: 'You can also write to me four times a year with your travel notebooks and the new itineraries.',
    merciTitre: 'Noted.',
    merciTexte: 'We come back to you within two working days with a suggested time. In the meantime, have a look at the journal, there are things we only say in writing.',
    merciBouton: 'Send another enquiry',
    asideTitre: 'Other ways to reach us.',
    parTelephone: 'By telephone',
    horaires: 'Mon to Sat, 10am to 6pm (Paris)',
    parEmail: 'By email',
    auBureau: 'At the office',
    adresse: '47 rue Vivienne',
    adresse2: '75002 Paris',
    adresse3: 'by appointment',
    carnet: 'Our notebook',
    carnetTexte: 'on Instagram, photos taken while scouting.',
  },

  journal: {
    eyebrow: 'THE JOURNAL',
    titre: 'What we write down when we get home.',
    lede: 'Travel notebooks, hand drawn maps, and now and then a rant about guidebooks made of plastic. A new piece roughly every three weeks.',
    posts: [
      { eyebrow: 'NOTEBOOK · MAY 2026', title: 'Three days without a phone on Yakushima.', kicker: 'And what we lost along the way.' },
      { eyebrow: 'NOTEBOOK · MARCH 2026', title: 'How we choose a ryokan.', kicker: 'or rather, how Hiroko-san chose for us.' },
      { eyebrow: 'NOTEBOOK · FEBRUARY 2026', title: "Mori-san's prewar kissaten, 47 years on.", kicker: 'We went back a third time.' },
      { eyebrow: 'NOTEBOOK · NOVEMBER 2025', title: 'Momiji: why October is too early.', kicker: 'And why we now plan for November.' },
    ],
  },

  cgv: {
    eyebrowVersion: 'Terms and conditions of sale',
    titre: 'What we undertake to do, and what we ask of you.',
    sousTitre: (v) => `Kiraku Travel, the joy of ease (喜楽). In force from ${v.vigueur}. This document cancels and replaces the version of ${v.remplace}.`,
    preambule: 'Preamble · identification of the operator',
    sommaire: 'Contents',
    question: 'A question? Write to us',
    pied: (v) => `${v.label} · in force on ${v.vigueur}.`,
    primaute: 'This is a translation provided for convenience. Only the French version of these terms is legally binding.',
  },
};
